%===============================%
Contents
1 Introduction to R 3
1.1 Installing R...... . . 3
1.2 Command Line Interface..... . 3
1.3 The Assignment operator..... . 4
1.3.1 Reserved Words..... . . 4
1.4 Commenting...... . . 4
1.5 Defining Variables.....5
1.6 Help Functions...... 5
1.7 The help.start() command.... . 5
1.8 Basic Maths Operations..... . 5
1.9 Basic R Editor...... 6
1.10 Built-In Data Sets..... . 6
1.11 The summary() command..... 7
1.12 Working directories..... . 7
1.13 Coming Unstuck.....7
1.14 Quitting the R environment....8
1.15 Data Objects...... . 8
1.16 Listing all items in a workspace.... 8
1.17 Removing items...... 8
1.18 Saving and Loading R Data Objects.... 8


1.4 Commenting
For the sake of readability, it is good practice to comment code. The # character at the
beginning of a line signifies a comment, which is not executed. Lines of hashtags can be used
to identify the beginning and end of code segments
# This is a comment
#####################
# Start of Segment 1
#####################
4
%===============================%
1.5 Defining Variables
A convention is to use define a variable name with a capital letter (R is case sensitive). This
reduces the chance of overwriting in-build R functions, which are usually written in lowercase
letters. Commonly used variable names such as x,y and z (in lower case letters) are not \re-
served".
