
6.4 filter()
filter() is an inclusive filter and requires the use of logical statements. In Chapter 2: Basic R I talked a little bit about logical statements. Here is a list of logical operators in R:



In addition to these logical operators, these functions can be used infilter():

is.na() - include if missing

!is.na() - include if not missing

between() - values that are between a certain range of numbers

near() - values that are near a certain value

We do not want to include practice trials when calculating the mean on RTs. We will use filter() to remove these rows. First let’s evaluate the values in these columns

unique(import$TrialProc)
## [1] "practice" "real"
unique(import$Condition)
## [1] "incongruent" "congruent"
We can specify our filter() in a couple of different ways

data <- filter(data, 
               TrialProc != "practice", 
               Condition != "neutral")
or

data <- filter(import, 
               TrialProc == "real", 
               Condition == "congruent" | Condition == "incongruent")
Specifying multiple arguments separated by a comma , in filter() is equivalent to an & (and) statement.

In the second option, since there are two types of rows on Condition that we want to keep we need to specify Condition == twice, separated by | (or). We want to keep rows where Condition == "congruent" or Condition == "incongruent"

Notice that the arguments have been separated on different lines. This is okay to do and makes it easier to read the code. Just make sure the end of the line still has a comma.

Go ahead and view data. Did it properly remove practice trials? How about neutral trials?

unique(data$TrialProc)
## [1] "real"
unique(data$Condition)
## [1] "incongruent" "congruent"
Again you should type these in the console NOT in the R Script!

There is a lot of consistency of how you specify arguments in the dplyr package.

You always first specify the data frame that the function is being performed on, followed by the arguments for that function.

Column names can be called just like regular R objects, that is without putting the column name in " " like you do with strings. If all you know is dplyr, then this might not seem like anything special but it is. Most non-tidyverse functions will require you to put " " around column names.
