Inspecting Data Frames
============================
<div class="chunk" id="unnamed-chunk-1"><div class="rcode"><div class="source"><pre class="knitr r"><span class="hl com">#inspecting the iris data set</span>

<span class="hl kwd">summary</span><span class="hl std">(iris)</span>
</pre></div>
<div class="output"><pre class="knitr r">##   Sepal.Length    Sepal.Width     Petal.Length    Petal.Width   
##  Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  
##  1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  
##  Median :5.800   Median :3.000   Median :4.350   Median :1.300  
##  Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199  
##  3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  
##  Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  
##        Species  
##  setosa    :50  
##  versicolor:50  
##  virginica :50  
##                 
##                 
## 
</pre></div>
</div></div>

<div class="chunk" id="unnamed-chunk-2"><div class="rcode"><div class="source"><pre class="knitr r"><span class="hl com">#Structure and Storage</span>

<span class="hl kwd">class</span><span class="hl std">(iris)</span>
</pre></div>
<div class="output"><pre class="knitr r">## [1] &quot;data.frame&quot;
</pre></div>
<div class="source"><pre class="knitr r"><span class="hl kwd">mode</span><span class="hl std">(iris)</span>
</pre></div>
<div class="output"><pre class="knitr r">## [1] &quot;list&quot;
</pre></div>
<div class="source"><pre class="knitr r"><span class="hl kwd">str</span><span class="hl std">(iris)</span>
</pre></div>
<div class="output"><pre class="knitr r">## 'data.frame':	150 obs. of  5 variables:
##  $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
##  $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
##  $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
##  $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
##  $ Species     : Factor w/ 3 levels &quot;setosa&quot;,&quot;versicolor&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...
</pre></div>
</div></div>

<div class="chunk" id="unnamed-chunk-3"><div class="rcode"><div class="source"><pre class="knitr r"><span class="hl com">###########################################</span>
<span class="hl com"># Dimensions of the iris data frame.</span>

<span class="hl kwd">dim</span><span class="hl std">(iris)</span>
</pre></div>
<div class="output"><pre class="knitr r">## [1] 150   5
</pre></div>
<div class="source"><pre class="knitr r"><span class="hl kwd">nrow</span><span class="hl std">(iris)</span>
</pre></div>
<div class="output"><pre class="knitr r">## [1] 150
</pre></div>
<div class="source"><pre class="knitr r"><span class="hl kwd">ncol</span><span class="hl std">(iris)</span>
</pre></div>
<div class="output"><pre class="knitr r">## [1] 5
</pre></div>
</div></div>

<div class="chunk" id="unnamed-chunk-4"><div class="rcode"><div class="source"><pre class="knitr r"><span class="hl com">###########################################</span>
<span class="hl com"># Row and Column names</span>

<span class="hl kwd">names</span><span class="hl std">(iris)</span>
</pre></div>
<div class="output"><pre class="knitr r">## [1] &quot;Sepal.Length&quot; &quot;Sepal.Width&quot;  &quot;Petal.Length&quot; &quot;Petal.Width&quot; 
## [5] &quot;Species&quot;
</pre></div>
<div class="source"><pre class="knitr r"><span class="hl kwd">rownames</span><span class="hl std">(iris)</span>
</pre></div>
<div class="output"><pre class="knitr r">##   [1] &quot;1&quot;   &quot;2&quot;   &quot;3&quot;   &quot;4&quot;   &quot;5&quot;   &quot;6&quot;   &quot;7&quot;   &quot;8&quot;   &quot;9&quot;   &quot;10&quot;  &quot;11&quot; 
##  [12] &quot;12&quot;  &quot;13&quot;  &quot;14&quot;  &quot;15&quot;  &quot;16&quot;  &quot;17&quot;  &quot;18&quot;  &quot;19&quot;  &quot;20&quot;  &quot;21&quot;  &quot;22&quot; 
##  [23] &quot;23&quot;  &quot;24&quot;  &quot;25&quot;  &quot;26&quot;  &quot;27&quot;  &quot;28&quot;  &quot;29&quot;  &quot;30&quot;  &quot;31&quot;  &quot;32&quot;  &quot;33&quot; 
##  [34] &quot;34&quot;  &quot;35&quot;  &quot;36&quot;  &quot;37&quot;  &quot;38&quot;  &quot;39&quot;  &quot;40&quot;  &quot;41&quot;  &quot;42&quot;  &quot;43&quot;  &quot;44&quot; 
##  [45] &quot;45&quot;  &quot;46&quot;  &quot;47&quot;  &quot;48&quot;  &quot;49&quot;  &quot;50&quot;  &quot;51&quot;  &quot;52&quot;  &quot;53&quot;  &quot;54&quot;  &quot;55&quot; 
##  [56] &quot;56&quot;  &quot;57&quot;  &quot;58&quot;  &quot;59&quot;  &quot;60&quot;  &quot;61&quot;  &quot;62&quot;  &quot;63&quot;  &quot;64&quot;  &quot;65&quot;  &quot;66&quot; 
##  [67] &quot;67&quot;  &quot;68&quot;  &quot;69&quot;  &quot;70&quot;  &quot;71&quot;  &quot;72&quot;  &quot;73&quot;  &quot;74&quot;  &quot;75&quot;  &quot;76&quot;  &quot;77&quot; 
##  [78] &quot;78&quot;  &quot;79&quot;  &quot;80&quot;  &quot;81&quot;  &quot;82&quot;  &quot;83&quot;  &quot;84&quot;  &quot;85&quot;  &quot;86&quot;  &quot;87&quot;  &quot;88&quot; 
##  [89] &quot;89&quot;  &quot;90&quot;  &quot;91&quot;  &quot;92&quot;  &quot;93&quot;  &quot;94&quot;  &quot;95&quot;  &quot;96&quot;  &quot;97&quot;  &quot;98&quot;  &quot;99&quot; 
## [100] &quot;100&quot; &quot;101&quot; &quot;102&quot; &quot;103&quot; &quot;104&quot; &quot;105&quot; &quot;106&quot; &quot;107&quot; &quot;108&quot; &quot;109&quot; &quot;110&quot;
## [111] &quot;111&quot; &quot;112&quot; &quot;113&quot; &quot;114&quot; &quot;115&quot; &quot;116&quot; &quot;117&quot; &quot;118&quot; &quot;119&quot; &quot;120&quot; &quot;121&quot;
## [122] &quot;122&quot; &quot;123&quot; &quot;124&quot; &quot;125&quot; &quot;126&quot; &quot;127&quot; &quot;128&quot; &quot;129&quot; &quot;130&quot; &quot;131&quot; &quot;132&quot;
## [133] &quot;133&quot; &quot;134&quot; &quot;135&quot; &quot;136&quot; &quot;137&quot; &quot;138&quot; &quot;139&quot; &quot;140&quot; &quot;141&quot; &quot;142&quot; &quot;143&quot;
## [144] &quot;144&quot; &quot;145&quot; &quot;146&quot; &quot;147&quot; &quot;148&quot; &quot;149&quot; &quot;150&quot;
</pre></div>
<div class="source"><pre class="knitr r"> <span class="hl com"># also try : rownames(mtcars)</span>
<span class="hl kwd">colnames</span><span class="hl std">(iris)</span>
</pre></div>
<div class="output"><pre class="knitr r">## [1] &quot;Sepal.Length&quot; &quot;Sepal.Width&quot;  &quot;Petal.Length&quot; &quot;Petal.Width&quot; 
## [5] &quot;Species&quot;
</pre></div>
</div></div>

<div class="chunk" id="unnamed-chunk-5"><div class="rcode"><div class="source"><pre class="knitr r"><span class="hl com">#############################################</span>
<span class="hl com"># The head() and tail() functions</span>

<span class="hl kwd">head</span><span class="hl std">(iris)</span>
</pre></div>
<div class="output"><pre class="knitr r">##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1          5.1         3.5          1.4         0.2  setosa
## 2          4.9         3.0          1.4         0.2  setosa
## 3          4.7         3.2          1.3         0.2  setosa
## 4          4.6         3.1          1.5         0.2  setosa
## 5          5.0         3.6          1.4         0.2  setosa
## 6          5.4         3.9          1.7         0.4  setosa
</pre></div>
<div class="source"><pre class="knitr r"><span class="hl kwd">tail</span><span class="hl std">(iris)</span>
</pre></div>
<div class="output"><pre class="knitr r">##     Sepal.Length Sepal.Width Petal.Length Petal.Width   Species
## 145          6.7         3.3          5.7         2.5 virginica
## 146          6.7         3.0          5.2         2.3 virginica
## 147          6.3         2.5          5.0         1.9 virginica
## 148          6.5         3.0          5.2         2.0 virginica
## 149          6.2         3.4          5.4         2.3 virginica
## 150          5.9         3.0          5.1         1.8 virginica
</pre></div>
<div class="source"><pre class="knitr r"><span class="hl kwd">head</span><span class="hl std">(iris,</span><span class="hl num">5</span><span class="hl std">)</span>
</pre></div>
<div class="output"><pre class="knitr r">##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1          5.1         3.5          1.4         0.2  setosa
## 2          4.9         3.0          1.4         0.2  setosa
## 3          4.7         3.2          1.3         0.2  setosa
## 4          4.6         3.1          1.5         0.2  setosa
## 5          5.0         3.6          1.4         0.2  setosa
</pre></div>
<div class="source"><pre class="knitr r"><span class="hl kwd">tail</span><span class="hl std">(iris,</span><span class="hl num">3</span><span class="hl std">)</span>
</pre></div>
<div class="output"><pre class="knitr r">##     Sepal.Length Sepal.Width Petal.Length Petal.Width   Species
## 148          6.5         3.0          5.2         2.0 virginica
## 149          6.2         3.4          5.4         2.3 virginica
## 150          5.9         3.0          5.1         1.8 virginica
</pre></div>
</div></div>

<div class="chunk" id="unnamed-chunk-6"><div class="rcode"><div class="source"><pre class="knitr r"><span class="hl com">#############################################</span>
<span class="hl com">#Accessing particular rows and columns</span>

<span class="hl std">iris[</span><span class="hl num">47</span><span class="hl std">,]</span> <span class="hl com"># 47th row</span>
</pre></div>
<div class="output"><pre class="knitr r">##    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 47          5.1         3.8          1.6         0.2  setosa
</pre></div>
<div class="source"><pre class="knitr r"><span class="hl std">iris[,</span><span class="hl num">2</span><span class="hl std">]</span>  <span class="hl com">#second column</span>
</pre></div>
<div class="output"><pre class="knitr r">##   [1] 3.5 3.0 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 3.7 3.4 3.0 3.0 4.0 4.4 3.9
##  [18] 3.5 3.8 3.8 3.4 3.7 3.6 3.3 3.4 3.0 3.4 3.5 3.4 3.2 3.1 3.4 4.1 4.2
##  [35] 3.1 3.2 3.5 3.6 3.0 3.4 3.5 2.3 3.2 3.5 3.8 3.0 3.8 3.2 3.7 3.3 3.2
##  [52] 3.2 3.1 2.3 2.8 2.8 3.3 2.4 2.9 2.7 2.0 3.0 2.2 2.9 2.9 3.1 3.0 2.7
##  [69] 2.2 2.5 3.2 2.8 2.5 2.8 2.9 3.0 2.8 3.0 2.9 2.6 2.4 2.4 2.7 2.7 3.0
##  [86] 3.4 3.1 2.3 3.0 2.5 2.6 3.0 2.6 2.3 2.7 3.0 2.9 2.9 2.5 2.8 3.3 2.7
## [103] 3.0 2.9 3.0 3.0 2.5 2.9 2.5 3.6 3.2 2.7 3.0 2.5 2.8 3.2 3.0 3.8 2.6
## [120] 2.2 3.2 2.8 2.8 2.7 3.3 3.2 2.8 3.0 2.8 3.0 2.8 3.8 2.8 2.8 2.6 3.0
## [137] 3.4 3.1 3.0 3.1 3.1 3.1 2.7 3.2 3.3 3.0 2.5 3.0 3.4 3.0
</pre></div>
<div class="source"><pre class="knitr r"><span class="hl std">iris[(</span><span class="hl num">1</span><span class="hl opt">:</span><span class="hl num">4</span><span class="hl std">), ]</span><span class="hl com">#first four rows</span>
</pre></div>
<div class="output"><pre class="knitr r">##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1          5.1         3.5          1.4         0.2  setosa
## 2          4.9         3.0          1.4         0.2  setosa
## 3          4.7         3.2          1.3         0.2  setosa
## 4          4.6         3.1          1.5         0.2  setosa
</pre></div>
</div></div>

<div class="chunk" id="unnamed-chunk-7"><div class="rcode"><div class="source"><pre class="knitr r"><span class="hl kwd">mean</span><span class="hl std">(iris</span><span class="hl opt">$</span><span class="hl std">Sepal.Length)</span>
</pre></div>
<div class="output"><pre class="knitr r">## [1] 5.843333
</pre></div>
<div class="source"><pre class="knitr r"><span class="hl kwd">median</span><span class="hl std">(iris</span><span class="hl opt">$</span><span class="hl std">Sepal.Width)</span>
</pre></div>
<div class="output"><pre class="knitr r">## [1] 3
</pre></div>
<div class="source"><pre class="knitr r"> <span class="hl kwd">levels</span><span class="hl std">(iris</span><span class="hl opt">$</span><span class="hl std">Species)</span>
</pre></div>
<div class="output"><pre class="knitr r">## [1] &quot;setosa&quot;     &quot;versicolor&quot; &quot;virginica&quot;
</pre></div>
</div></div>



</body>
</html>
