---
title: Importing Data into R
author: DragonflyStats.github.io
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Type to search (Enter for navigation)
EngleLab: useRguide
Welcome
I Getting Started in R
1 Installation
2 Basic R
3 Intermediate R
II Working with Data
4 Tidyverse
5 Read and Write Data
6 Data Manipulation using dplyr
6.1 Setup
6.2 Import
6.3 rename()
6.4 filter()
6.5 select()
6.6 mutate()
6.7 case_when()
6.8 group_by()
6.9 summarise()
6.10 pivot_wider()
6.11 pivot_longer()
6.12 Pipe Operator %>%
7 Common Data Manipulations
III Analyzing Data
8 Project Organization
9 Import and Output Data Files
10 Tidy Raw Data
11 Score and Clean Data
12 Single Merged File
13 A Masterscript
IV Data Visualization
Data Visualization: Overview
14 Fundamentals of Data Visualization
15 Introduction to ggplot2
16 Scatterplots
17 Plotting Means
18 Univariate Plots
V Statistical Analysis
Statistical Analysis: Overview
19 Statistics in R
20 Structural Equation Modelling
Cheatsheet
EngleLab: useRguide
6 Data Manipulation using dplyr
In this Chapter you will learn the fundamentals of data manipulation in R. In the Getting Started in R section you learned about the various types of objects in R. The most important object you will be using is the dataframe. Last Chapter you learned how to import data files into R as dataframes. Now you will learn how to do stuff to that data frame using the dplyr package (which is of course part of the tidyverse)



dplyr is one of the most useful packages in R. It uses a Grammar of Data Manipulation that is intuitive and easy to learn. The language of dplyr will be the underlying framework for how you will think about manipulating a dataframe.

Not only is the language of dplyr intuitive but it allows you to perform data manipulations all within the dataframe itself, without having to create external variables, lists, for loops, etc.

It can be tempting to hold information outside of a data frame but in general I suggest avoiding this strategy. Instead, hold the information in a new column within the data frame itself.

For example: A common strategy I see any many R scripts is to hold the mean or count of a column of values outside the dataframe and in a new variable in the Environment.

data <- data.frame(x = c(1,6,4,3,7,5,8,4), y = c(2,3,2,1,4,6,4,3))

x_mean <- mean(data$x)
This variable then could be used to subtract out the mean from the values in column y

data <- mutate(data, y_new = y - x_mean)
head(data)
##   x y y_new
## 1 1 2 -2.75
## 2 6 3 -1.75
## 3 4 2 -2.75
## 4 3 1 -3.75
## 5 7 4 -0.75
## 6 5 6  1.25
mutate() is a dplyr function you will learn about in a second.

In general, I would advise against this strategy. A better strategy is to do all this without leaving the data frame data.

data <- data.frame(x = c(1,6,4,3,7,5,8,4), y = c(2,3,2,1,4,6,4,3))
data <- mutate(data,
               x_mean = mean(x),
               y_new = y - x_mean)
head(data)
##   x y x_mean y_new
## 1 1 2   4.75 -2.75
## 2 6 3   4.75 -1.75
## 3 4 2   4.75 -2.75
## 4 3 1   4.75 -3.75
## 5 7 4   4.75 -0.75
## 6 5 6   4.75  1.25
It can tempting to also think about writing for loops in your R script, but honestly for the most part for loops are avoidable thanks to a dplyr function called group_by().

The only time I end up needing a for loop is when importing a long list of files, or when creating code to put into a function.

dplyr uses intuitive language that you are already familiar with. As with any R function, you can think of functions in the dplyr package as verbs - that refer to performing a particular action on a data frame. The core dplyr functions are:

rename() renames columns

filter() filters rows based on their values in specified columns

select() selects (or removes) columns

mutate() creates new columns based on transformation from other columns, edits values within existing columns

group_by() splits data frame into separate groups based on specified columns

summarise() aggregates across rows to create a summary statistic (means, standard deviations, etc.)

For more information on these functions Visit the dplyr webpage

If you have not done so already, install the dplyr package

install.packages("dplyr")
You will also need the tidyr package (a tidyverse package) for this Chapter

install.packages("tidyr")

Save a new R script file as 5_dplyr.R

For this Chapter we will use an example data set from the Flanker task. This data set is a tidy raw data file for over 100 subjects on the Flanker task. There is one row per Trial per Subject and there is RT and Accuracy data on each Trial. Each Trial is either congruent or incongruent.

What we will want to do is calculate a FlankerEffect for each Subject so that we end up with one score for each Subject.

Go ahead and download the example data set and save it wherever you wish. We will talk about how to organize your data and R scripts in section III. Workflow.


Download Example Tidyverse Data

6.1 Setup
At the top of your script load the three packages you will need for this Chapter

## Setup
library(readr)
library(dplyr)
library(tidyr)
Notice how I added a commented line at the top. Adding comments to your scripts is highly advisable, as it will help you understand your scripts when you come back to them after not working on them for a while. You only need to add a single # to create a commented line.

You will also notice that it printed out some warning messages. Sometimes different packages have the same function names. So when you load a package it may override or mask functions from other packages that are already loaded.

