---
title: Introduction to R
author: DragonflyStats.github.io
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## What is R?

* {Introduction to R}
* Source: R project website (http://www.r-project.org)

* R is a language and environment for statistical computing and graphics. It is a GNU project
which is similar to the S language and environment which was developed at Bell Laboratories
(formerly AT\&T, now Lucent Technologies) by John Chambers and colleagues. 
* R can be considered
as a different implementation of S. There are some important differences, but much
code written for S runs unaltered under R.

Introduction to Statistical Computing
Broadly speaking, the aim of statistics is to understand data and the relationships between variables. Due to the growth in information technology, data sets have grown considerably as the capacity for data collection and storage has increased.
 
In addition, computer processors are more affordable, so that most modern applied statisticians are involved in computing. To analyse data, statisticians and programmers have developed statistical software and
programming languages.
 
A good example is the S Programming Language, which was designed especially for programming with data. There are now a large number of software libraries written in S which can be used to solve almost any practical statistical problem.
 
To start R in Windows, double click the R icon. To start R in Unix or Linux, type ‘R’ at the command prompt. To get out of R, just type: q().
R has an inbuilt help facility. To get more information on any specific named
function, for example “boxplot”, the command is:
?boxplot
 
 
R has data handling and storage facilities, a suite of operators for calculations on arrays in particular matrices. A large coherent integrated collection of intermediate tools for data analysis
A large selection of demonstration datasets used in the illustration of many statistical methods.
Graphical facilities for data analysis and display either directly.at the computes or on hardcopy.
 
 



* R provides a wide variety of statistical (linear and nonlinear modelling, classical statistical tests,
time-series analysis, classification, clustering, ...) and graphical techniques, and is highly extensible.
* The S language is often the vehicle of choice for research in statistical methodology,
and <tt>R</tt> provides an Open Source route to participation in that activity.
* One of <tt>R</tt>’s strengths is the ease with which well-designed publication-quality plots can be
produced, including mathematical symbols and formulae where needed. 


## Introduction to R

* R is the product of an active movement among statisticians for a powerful, programmable, portable, and open computing environment, applicable to the most complex and sophsticated problems, as well as“routine”analysis.
 
* There are no restrictions on access or use.

* Statisticians have implemented hundreds of specialised statistical procedures for a wide variety of applications as contributed packages, which are also freely-available and which integrate directly into R.

 
* R has data handling and storage facilities, a suite of operators for calculations on arrays in particular matrices. A large coherent integrated collection of intermediate tools for data analysis
* A large selection of demonstration datasets used in the illustration of many statistical methods.
* Graphical facilities for data analysis and display either directly.at the computes or on hardcopy.
 

* R is a flexible language that is object oriented and thus allows the manipulation of a complex data structures in a condensed and efficient manner.

* R's graphical abilities are also remarkable with possible interfacing with text processors such as Latex with the package sweave.

* R offers the addtional advantage of being a free and opensource system under the GNU general public licence.

* R is primarily a statistical language. R can be installed free of charge from www.r-project.org

------------------------------------

### Getting Started

* An online guide "An Introduction to R" can be access by typing help.start() at the command prompt to access this.

* R is a statistical Environment for statistical computing and graphics, which is available for windows, Unix and Mac OS platforms.

* R is maintained and distributed by an international team of statisticians and computers scientists.

* R is one of the major tools used in statistical research and in applications of statistics research.

* R is an open-source (GPL) statistical environment modeled after S and S-Plus. The S language was developed in the late 1980s at AT&T labs. The R project was started by Robert Gentleman and Ross Ihaka of the Statistics Department of the University of Auckland in 1995. It has quickly gained a widespread audience. 

----------------------------------------------------------------------

### Who Manages R?

* R is currently maintained by the R core-development team, a hard-working, international team of volunteer developers. 

The R project web page ( http://www.r-project.org ) is the main site for information on R. At this site are directions for obtaining the software, accompanying packages and other sources of documentation.


