6.6 mutate()
mutate() is a very powerful function. It basically allows you to do any computation or transformation on the values in the data frame. You can

change the values in already existing columns

create new columns based on transformation of other columns

6.6.1 Changing values in an existing column
Reaction times that are less than 200 milliseconds most likely do not reflect actual processing of the task. Therefore, it would be a good idea to not include these when calculating means.

What we are going to do is is set any RTs that are less than 200 milliseconds to missing, NA. First let’s make sure we even have trials that are less than 200 milliseconds. Two ways to do this. 1) View the data frame and click on the RT column to sort by RT. You can see there are RTs that are as small as 1 millisecond! Oh my, that is definitely not a real reaction time. 2) you can just evaluate the minimum value in the RT column:

min(data$RT)
## [1] 0
Now lets mutate()

data <- mutate(data, RT = ifelse(RT < 200, NA, RT))
Since we are replacing values in an already existing column we can just specify that column name, RT = followed by the transformation. Here we need to specify an if…then… else statement. To do so within the mutate() function we use the function called ifelse().

ifelse() evaluates a logical statement specified in the first argument, RT < 200. mutate() works on a row-by-row basis. So for each row it will evaluate whether RT is less than 200. If this logical statement is TRUE then it will perform the next argument, in this case sets RT = NA. If the logical statement is FALSE then it will perform the last argument, in this case sets RT = RT (leaves the value unchanged).

6.6.2 Creating a new column
Let’s say for whatever reason we want to calculate the difference between the RT on a trial minus the overall grand mean RT (for now, across all subjects and all trials). This is not necessary for what we want in the end but what the heck, let’s be a little crazy. (I just need a good example to illustrate what mutate() can do.)

So first we will want to calculate a “grand” mean RT. We can use the mean() function to calculate a mean.

mean(data$RT, na.rm = TRUE)
## [1] 529.1414
Since we replaced some of the RT values with NA we need to make sure we specify in the mean() function to remove NAs by setting na.rm = TRUE.

We can use the mean() function inside of a mutate() function. Let’s put this “grand” mean in a column labeled grandRT.

First take note of how many columns there are in data

ncol(data)
## [1] 5
So after calculating the grandRT we should expect there to be one additional column for a total of 6 columns

data <- mutate(data, grandRT = mean(RT, na.rm=TRUE))
Cool!

Now let’s calculate another column that is the difference between RT and grandRT.

data <- mutate(data, RTdiff = RT - grandRT)
We can put all these mutate()s into one mutate()

data <- mutate(data, 
               RT = ifelse(RT < 200, NA, RT),
               grandRT = mean(RT, na.rm = TRUE),
               RTdiff = RT - grandRT)
Notice how I put each one on a separate line. This is just for ease of reading and so the line doesn’t extend too far off the page. Just make sure the commas are still there at the end of each line.

