
6.10 pivot_wider()
Our data frame now looks like

head(data)
## # A tibble: 6 x 4
##   Subject Condition   RT.mean ACC.mean
##     <dbl> <chr>         <dbl>    <dbl>
## 1   14000 congruent      401.    0.931
## 2   14000 incongruent    510.    0.574
## 3   14001 congruent      392.    0.980
## 4   14001 incongruent    423.    0.852
## 5   14002 congruent      462.    0.765
## 6   14002 incongruent    536.    0.463
Ultimately, we want to have one row per subject and to calculate the difference in mean RT between incongruent and congruent conditions. It is easier to calculate the difference between two values when they are in the same row. Currently, the mean RT for each condition is on a different row. What we need to do is reshape the data frame. To do so we will use the pivot_wider() function from the tidyr package.

The tidyr package, like readr and dplyr, is from the tidyverse set of packages. The pivot_wider() function will convert a long data frame to a wide data frame. In other words, it will spread values on different rows across different columns.

In our example, what we want to do is pivot_wider() the mean RT values for the two conditions across different columns. So we will end up with is one row per subject and one column for each condition. Rather than incongruent, and congruent trials being represented down rows we are spreading them across columns (widening the data frame).

The three main arguments to specify in pivot_wider() are

id_cols: The column names that uniquely identifies (e.g. “Subject”) each observation and that you want to be retained when reshaping the data frame.

names_from: The column name that contains the variables to create new columns by (e.g. “Condition”). The values in this column will become Column names in the wider data format

values_from: The column name that contains the values (e.g. “RT”).

data_wide <- pivot_wider(data, 
                         id_cols = "Subject",
                         names_from = "Condition", 
                         values_from = "RT.mean")
Now our data frame looks like

head(data_wide)
## # A tibble: 6 x 3
##   Subject congruent incongruent
##     <dbl>     <dbl>       <dbl>
## 1   14000      401.        510.
## 2   14001      392.        423.
## 3   14002      462.        536.
## 4   14003      567.        679.
## 5   14004      548.        655.
## 6   14005      472.        559.
Notice that the ACC.mean column and values were dropped. To add more transparency to our data frame it would be a good idea to label what values the “congruent” and “incongruent” columns contain. You can do this with the optional names_prefix argument. For instance:

data_wide <- pivot_wider(data, 
                         id_cols = "Subject",
                         names_from = "Condition", 
                         values_from = "RT.mean",
                         names_prefix = "RT_")
head(data_wide)
## # A tibble: 6 x 3
##   Subject RT_congruent RT_incongruent
##     <dbl>        <dbl>          <dbl>
## 1   14000         401.           510.
## 2   14001         392.           423.
## 3   14002         462.           536.
## 4   14003         567.           679.
## 5   14004         548.           655.
## 6   14005         472.           559.
Now a stranger (or a future YOU) will be able to look at this data frame and immediately know that reaction time values are contained in these columns.

From here it is pretty easy, we just need to create a new column that is the difference between incongruent and congruent columns. We can use the mutate() function to do this

data_wide <- mutate(data_wide, FlankerEffect_RT = RT_incongruent - RT_congruent)
head(data_wide)
## # A tibble: 6 x 4
##   Subject RT_congruent RT_incongruent FlankerEffect_RT
##     <dbl>        <dbl>          <dbl>            <dbl>
## 1   14000         401.           510.            109. 
## 2   14001         392.           423.             31.3
## 3   14002         462.           536.             74.0
## 4   14003         567.           679.            113. 
## 5   14004         548.           655.            107. 
## 6   14005         472.           559.             87.1
Perfect! Using the readr, dplyr, and tidyr packages we have gone from a “tidy” raw data file to a data frame with one row per subject and a column of FlankerEffect scores.

What if we have multiple columns we want to get id_cols, names_from, or values_from? pivot_wider() allows for this very easily. For instance:

data_wide <- pivot_wider(data, 
                         id_cols = "Subject",
                         names_from = "Condition", 
                         values_from = c("RT.mean", "ACC.mean"))
head(data_wide)
## # A tibble: 6 x 5
##   Subject RT.mean_congruent RT.mean_incongruent ACC.mean_congruent ACC.mean_incongruent
##     <dbl>             <dbl>               <dbl>              <dbl>                <dbl>
## 1   14000              401.                510.              0.931               0.574 
## 2   14001              392.                423.              0.980               0.852 
## 3   14002              462.                536.              0.765               0.463 
## 4   14003              567.                679.              0.294               0.0926
## 5   14004              548.                655.              0.5                 0.0370
## 6   14005              472.                559.              0.686               0.204
Now you can see that we have four columns corresponding to reaction times and accuracy values across the two conditions. You can use the same notation c() if you want to use multiple column for id_cols, names_from, values_from.

Now we can calculate a FlankerEffect for both RT and Accuracy values

data_wide <- mutate(data_wide, 
                    FlankerEffect_RT = RT.mean_incongruent - RT.mean_congruent,
                    FlankerEffect_ACC = ACC.mean_incongruent - ACC.mean_congruent)
