Base Graphics {data-navmenu="R Graphics"}
==========================================================
Column {.tabset}
--------------------------------------

### Enhancing your scatter plots

<h3> Adding lines </h3>
Previously we have used scatter plots to plot bivariate data. They were constructed using the ``plot()`` command.
Recall that we can use the arguments ``xlim`` and ``ylim`` to control the vertical and horizontal range of the plots, by specifying a two element vector (min and max) for each.

Using the ``abline()`` command, we can add lines to our scatter plots. We specify the argument according to the type of line required. A demonstration of three types of line is provided below.
Additionally we change the colour of the added lines, by specifying a colour in the ``col`` argument. We can also change the line type to one of four possible types, using the ``lty`` argument.

The line types are follows

* ``lty =1``   Normal full line (default)
* ``lty =2``   Dashed line
* ``lty =3``   Dotted line
* ``lty =4``   Dash-dot line

<pre><code>
x=rnorm(10)
y=rnorm(10)
plot(x,y)
plot(x,y,xlim=c(-4,4),ylim=c(-4,4))
abline(v =0 , lty =2 )    # add a vertical dotted line (here the y-axis) to the plot
abline(h=0  ,lty =3)    # add a horizontal dotted line (here the x-axis) to the plot
abline(a=0,b=1,col="green") # add a line to your plot with intercept "a" and slope "b"
</code></pre><p>

<h3> Changing your plot character</h3> 

To change the plot character (the symbol for each covariate, we supply an additional argument to the plot() function.  This argument is formulated as pch=n where n is some number.
Additionally we change the colour of the characters, by specifying a colour in the col argument.
<p> <pre><code>
plot(x,y,pch=15,col="red")#Square plot symbols
plot(x,y,pch=16,col="green")#Orb plot symbols
plot(x,y,pch=17,col="mauve")#Triangular plot symbols
plot(x,y,pch=36,col="amber")#Dollar sign plot symbols
</code></pre><p>
Recall that we can add new variates to an existing scatterplot using the points() function. Remember to set the vertical and horizontal limits accordingly.
<p> <pre><code>
y1 = rnorm(10); y2 = rnorm(10)
plot(x,y1, pch=8,col="purple" ,xlim=c(-5,5),ylim=c(-5,5))
points(x,y2,pch=12,col="green")
</code></pre>
<p>
<h3>Adding the regression model line</h3>

The ``abline()`` function can be used to add a regression model line  by supplying as an argument the ``coef()`` values for intercept and slope estimates .These estimates can be inputted directly by using both functions in conjunction.

<p> <pre><code>
Fit1 =lm(y1~x);  coef(Fit1)
abline(coef(Fit1))
</code></pre><p>

<h3>Adding a title </h3>

It is good practice to label your scatterplots properly. You can specify the following argument
\begin{itemize}
* main="Scatterplot Example", This provides the plot with a title
* sub="Subtitle",                 This adds a subtitle
* xlab="X variable ",This command labels the x axis 
*    ylab="y variable ",This command labels the y-axis
\end{itemize}
We can also add text to each margin, using the ``mtext()`` command.  
We simply require the number of the side. (1 = bottom, 2=left,3=top,4=right). 
We can change the colour using the col argument.

<pre><code>
plot(x,y,main="Scatterplot Example",   sub="subtitle",    xlab="X variable ", ylab="y variable ")
mtext("Enhanced Scatterplot", side=4,col="red ")
</code></pre><p>
Alternatively , we can also use the command title() to add a title to an existing scatterplot.
<p> <pre><code>
title(main="Scatterplot Example)
</code></pre>
<p>
  
<h3>Combining plots</h3>
It is possible to combine two plots. We used the graphical parameters command ``par()`` to create an array. 
Often we just require two plots side by side or above and below. We simply specify the numbers of rows and columns of this array using the ``mfrow`` argument, passed as a vector.

<pre><code>
par(mfrow=c(1,2))
plot(x,y1)# draw first plot
plot(x,y2)# draw second plot
par(mfrow=c(1,1))# reset to default setting.
</code></pre>

### Plot of single vectors
If only one vector is specified i.e. ``plot(x)``,  the plot created will simply be a scatter-plot of the values of x against their indices.

$plot(x)$
Suppose we wish to examine a trend that these points represent. We can connect each covariate using a line.

$plot(x, type = "l")$
If we wish to have both lines and points, we would input the following code. This is quite useful if we wish to see how a trend develops over time.
$plot(x, type = "b")$

