

## Basic R editing – Script Editor and \texttt{edit()}}
R has an inbuilt script editor. We will use it for this class, but there are plenty of top quality “Integrated Development Environments “ out there. (Read up about RStudio for  example.)

To start a new script, or open an existing script simply go to “File” on the menu bar and click the appropriate options.
A new dialogue box will appear. You can write and edit code using this editor.
To pass the code for compiling – press the “run line or selection” option (The third icon on the menu).
Another way to edit code is to use the \texttt{edit()} function – which operates directly from the command line.  
To edit the code defining an object X, simply type edit(X).
%------------------------------------------------------%
## Changing GUI options}
We can change the GUI options using the “GUI preferences” option on the Edit menu. (Important when teaching R)
A demonstration will be done in class. 


The command \texttt{summary()} is one of the most useful commands in R. It is a generic function used to produce result summaries of the results of various functions. The function invokes particular methods which depend on the class of the first argument. 
In other words – <tt>R</tt> picks out the most suitable type of summary for that data.
{
	\small

\begin{verbatim}
> summary(iris)
  Sepal.Length    Sepal.Width     Petal.Length    Petal.Width          Species  
 Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100   setosa    :50  
 1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300   versicolor:50  
 Median :5.800   Median :3.000   Median :4.350   Median :1.300   virginica :50  
 Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199                  
 3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800                  
 Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500                  
>
\end{verbatim}

}

%---------------------------------------------------------------------------------------------%
\texttt{summary()} is particularly useful for manipulating data from more complex data objects.
Working directories
You can change your working directly by using the appropriate options on the File menu.
To determine the current working directory – you can use the \texttt{getwd()} command:	

\begin{verbatim}
> getwd()
[1] "C:/Users/Kevin/Documents"
\end{verbatim}

To change the working directory – we would use the \texttt{setwd()} command.

\begin{verbatim}
> getwd()
[1] "C:/Users/Kevin"
>
> setwd("C:/Users/Kevin/Documents")
>
> getwd()
[1] "C:/Users/Kevin/Documents"
\end{verbatim}


%---------------------------------------------------------------------------------------------%
\subsection*{Coming unstuck}
If you are having trouble with a piece of code that is currently compiling – all you have to do is press ESC. Just like other computing environments.



