
## The R Programming Language

The R Programming Language is a statistical , data analysis , etc

R is a free software environment for statistical computing and graphics.

----------------------------------------------------------------------------------
General Rules
· Prompt for commands in command window: >
· Continuation prompt when command incomplete: +
· Neither of these ever typed by user
· Command can be any length
· If you want to break a long command into multiple lines for readability, make sure R knows that more is to come by making the current line incomplete (Example: end the line with one of the three characters ({,)
· Multiple commands may appear on one line if separated by ;

## Vector types}
<tt>R</tt> operates on named data structures. The simplest such structure is the
vector, which is a single entity consisting of an ordered collection of
Numbers or characters.


*  Numeric vectors
*  Character vectors
*  Logical vectors
*  (also complex number vectors and colour vectors)


To create a vector, use the assignment operator and the concatenate function.
For numeric vectors, the values are simply numbers.

\begin{verbatim}
># week8.r
>NumVec<-c(10.4,5.6,3.1,6.4)
\end{verbatim}

Alternatively we can use the \texttt{assign()} command

For character vectors, the values are simply characters, specified with
quotation marks.A logical vectors is a vector whose elements are TRUE, FALSE or NA

\begin{verbatim}
>CharVec<-c(``blue", ``green", ``yellow")
>LogVec<-c(TRUE, FALSE)
\end{verbatim}

---------------------------------------

Another method of creating vectors is to use the following
\begin{verbatim}
numeric (length = n)
character (length = n)
logical (length = n)
\end{verbatim}
These commands create empty vectors, of the appropriate kind, of length $n$. You can then use the graphical data entry interface to populate your data sets.

\subsubsection{Accessing specified elements of a vector}

The $n$th element of vector ``Vec" can be accessed by specifying its index when
calling ``Vec".
\begin{verbatim}>Vec[n]
\end{verbatim}
A sequence of  elements of vector ``Vec" can be accessed by specifying its index
when calling ``Vec".
\begin{verbatim}>Vec[l:u]
\end{verbatim}
Omitting and deleting the $n$th element of vector ``Vec"
\begin{verbatim}
>Vec[-n]
>Vec <- Vec[-n]
\end{verbatim}

%### Reading data}


### inputting data}
 Concatenation

### using help}

?mean

%### Adding comments}

### Packages}
The capabilities of R are extended through user-submitted packages, which allow specialized statistical techniques, graphical devices, as well as and
import/export capabilities to many external data formats.
