

### Functions
Syntax to define functions

<pre>
<code>
myfct <- function(arg1, arg2, ...) { function_body }
</code>
</pre>
The value returned by a function is the value of the function body, which is usually an unassigned final expression, e.g.: return()

Syntax to call functions
<pre>
<code>
myfct(arg1=..., arg2=...)
</code>
</pre>


\section{Time and Date}
It is useful . The length of time a program takes is interesting.


<pre>
<code>
date() # returns the current system date and time
</code>
</pre>


\section{The Apply family}

Sometimes want to apply a function to each element of a
vector/data frame/list/array.
\\
Four members: lapply, sapply, tapply, apply
\\
lapply: takes any structure and gives a list of results (hence
the `l')
\\
sapply: like lapply, but tries to simplify the result to a
vector or matrix if possible (hence the `s')
\\
apply: only used for arrays/matrices
\\
tapply: allows you to create tables (hence the `t') of values
from subgroups defined by one or more factors.
\newpage
\chapter{Data Visualization}
\section{Plots}
This section is an introduction for producing simple graphs with
the R Programming Language.
\begin{itemize}
*  Line Charts  *  Bar Charts *  Histograms *  Pie
Charts *  Dotcharts
\end{itemize}

