
### {Section 3 - Inspecting a Data Set }
 
*  [3.1] Dimensions of a data set 
*  [3.2] The <tt>summary()</tt> command   
*  [3.3] Structure of a Data Object 
 
### Section 4 : Packages}


 %  4.1 Packages 
 %  4.2 Using and Installing packages 
 %  4.2.1 Version of R 
 %  end{semiverbatim}
 %
 % 
 %

### {Section 3 Inspecting a Data Set}

### Summary of useful commands}
 
*  <tt>dim()</tt> and <tt>length()</tt>
*  <tt>nrow()</tt> and <tt>ncol()</tt>
*  <tt>names()</tt>
*  <tt>summary()</tt>
*  <tt>tail()</tt>
*  <tt>head()</tt>
*  <tt>describe()</tt> (from the textbf{psych} package)
 

 
### {3.1 Dimensions of a data set}
 
*  We have remarked that some data sets are very large. 
*  This is perhaps a good place to consider
 summary information about data objects. 
*  For a simple vector, a useful command to determine
 the length (remark: sample size) is the function <tt>length()</tt>.
 
 <pre>
 <tt>Y=4:18}
 <tt>length(Y)}
 
 </pre>
<p>
 For more complex data sets ( and data frames which we will see later) , we have several
 tools for assessing the size of data.
 
<p>


### {Column (Variable) names and Row names}
 
*  We can also determine the row names and column names using the functions <tt>rownames()</tt>
 and <tt>colnames()</tt>. 
*  If there are no specific row or column names, the command will just return
 the indices.
