---
title: "Granger Causality test"
subtitle: "Programming with R"
author: DragonflyStats.github.io
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(digits=3)
```


#### Introducton to R

"summary" is a generic function used to produce result summaries of the results of various model fitting functions. 
The function invokes particular methods which depend on the class of the first argument. 

  *   attach()
  *   data()
   *   Loads specified data sets, or list the available data sets. 
  *   ?
  *   data.entry
  *   c()


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Combine Values into a Vector or List

  *   assignment operator
  *   Sys.time and Sys.Date returns the system's idea of the current date with and without time. 
  *   q()


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#### Introducton to R : mode and class}


 * [\texttt{mode()}]  storage mode of a data object( data structure)
* [\texttt{class()}] class
\end{description}



The expression as(object, value) is the way to coerce an object to a particular class. 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#### Introducton to R}


basic R editor

 *   new script
 *   updating script
 *   running script
 *  



*   Combine Values into a Vector or List
  *   assignment operator
  *   Sys.time and Sys.Date returns the system's idea of the current date with and without time. 
  *   q()
 



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#### Introducton to R}


vectors

vector produces a vector of the given length and mode.
as.vector, a generic, attempts to coerce its argument into a vector of mode mode (the default is to coerce to whichever mode is most convenient).
is.vector returns TRUE if x is a vector of the specified mode having no attributes other than names. It returns FALSE otherwise.  

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#### Introducton to R}
integer
Creates or tests for objects of type "integer".
integer(length = 0)
as.integer(x, ...)
is.integer(x)


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#### Introducton to R}

 Character
Create or test for objects of type "character".
character(length = 0)
as.character(x, ...)
is.character(x)



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#### Introducton to R}

logical
Create or test for objects of type "logical", and the basic logical constants.
logical(length = 0)
as.logical(x, ...)
is.logical(x)


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#### Introducton to R}

numeric
Creates or coerces objects of type "numeric". 
numeric(length = 0)
as.numeric(x, ...)
is.numeric(x)



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#### Introducton to R :  Lists}



   *   list() Functions to construct, coerce and check for both kinds of R lists. 
 *   vectors
 *   dataframes

------------------------------------------

#### Introducton to R

Packages


 *   What are pacakges
*   extending the program
 *   where are packages to be found
 *   some notable packages
 *   installing packages
 *   loading packages
 *   updating packages


