
 %==============================================================================================%
 

 includegraphics[width=0.9linewidth]{Rlogo}

 

 Source: R project website (http://www.r-project.org)
 



textbf{Secton 1 - A few basics} 

*  [1.1] Installing ***R***      
*  [1.2] Command Line Interface     
*  [1.3] The Assignment operator     
*  [1.4] Commenting      
*  [1.5] Defining Variables     
*  [1.6] Help Functions      
*  [1.7] The texttt{help.start()} command     
*  [1.8] Basic Maths Operations     
*  [1.9] Basic ***R*** Editor      
 
 
### {1.1 Installing R}
 
*  ***R*** is very easily installed by downloading it from the CRAN website. Installation usually takes
 about 2 minutes. 
*  When installation of R is complete, the distinctive ***R*** icon will appear on your
 desktop. To start ***R***, simply click this Icon. 
*  It is common to re-install ***R*** once a year or so. The
 current version of ***R***, version 3.1.2 was released quite recently.
 
 
 

 
### {1.9 Basic ***R*** Editor}
 
*  ***R*** has an inbuilt script editor. We will use it for this class, but there are plenty of top quality
 Integrated Development Environments out there. (Read up about textbf{RStudio} for example).
*  For a while, we will use the in-built script editor. Although it is advisable to start using textbf{Rstudio} or something similar in the not-too-distant future.
 
 
 
 
 %==============================================================================================%
 
 % % SLIDE 1 - COVER SLIDE
 begin{figure}
 centering
 includegraphics[width=1.2linewidth]{images/Rscript}         
 end{figure}
    
 %==============================================================================================%
 
### {1.9 Basic ***R*** Editor}
 
*  To start a new script, or open an existing script simply go to File and click the appropriate
 options. A new dialogue box will appear. 
 
*  You can write and edit code using this editor.
*  To pass the code for compiling , press the run line or selection option (The third icon
 on the menu).
 
 
 %==============================================================================================%
 
 
 
*  Another way to read code is to use the texttt{edit()} function, which operates directly from the
 command line. 
*  To see how the code defining an object X was written (or more importantly,
 could have been written) simply type texttt{edit(X)}. 
*  This command has some useful applications
 that we will see later on (the texttt{scan()} command).
 
 
 
### {Script Files}
 
*  Scripts are saved as texttt{.R} files. 
*  These scripts can be called directly using the texttt{source()} command.
 
 
 <pre>
 texttt{source(myScript.R)}
 
 texttt{source(myDatasets.R)}
 
 texttt{source(myFunctions.R)}
 </pre>
<p>
 
 
 
 
 
