## ``number_bytes_format`` Bytes formatter: convert to byte measurement and display symbol.
#### Description
Bytes formatter: convert to byte measurement and display symbol.
#### Usage
<pre><code>
number_bytes_format(symbol = "auto", units = "binary", ...)
number_bytes(x, symbol = "auto", units = c("binary", "si"), ...)
</code></pre>
  
#### Arguments
symbol byte symbol to use. If "auto" the symbol used will be determined by the maximum
value of x. Valid symbols are "b", "Kb", "Mb", "Gb", "Tb", "Pb", "Eb",
"Zb", and "Yb", along with their upper case equivalents and "iB" equivalents.
units which unit base to use, "binary" (1024 base) or "si" (1000 base) for ISI units.
... Other arguments passed to number()
x a numeric vector to format
Value
a function with three parameters, x``, a numeric vector that returns a character vector,symbolthe byte symbol for ISI metric units).

#### Examples
```{r}
number_bytes_format()(sample(3000000000, 10))
number_bytes(sample(3000000000, 10))
number_bytes(sample(3000000000, 10), accuracy = .1)
```

#### References
Units of Information (Wikipedia) : http://en.wikipedia.org/wiki/Units_of_information
