
## The paired t-test 


*  Previously we have seen the paired t-test. It is used to determine whether or
not there is a significant difference between paired measurements. Equivalently whether or not
the case-wise differences are zero.
*  The mean and standard deviation of the case-wise differences are used to determine the test statistic.
*  Under the null hypothesis, the expected value of the case-wise differences is zero (i.e $H_0 : \mu_d = 0$).
*  The test statistic is computed as
\[ TS = \frac{\bar{d} - \mu_d}{\frac{s_d}{\sqrt{n}}} \]

### The Paired $t$-Test (b)}

*  The calculation is dependent on the case-wise differences.
*  Here the case-wise differences between paired measurements (e.g. ``before" and ``after").
*  Under the null hypothesis, the mean of case-wise differences is zero.
*  As a quick example, the mean, standard deviation and sample size are presented in the next slide.


### The Paired $t$-Test (c)

*  Observed Mean of Case-wise differences $\bar{d}$ = 8.21,
*  Expected Mean of Case-wise differences under $H_0$ : $\mu_d = 0$,
*  Standard Deviation of Case-wise differences $S_d$ = 7.90,
*  Sample Size $n=14$.


\[ TS = \frac{\bar{d} - \mu_d}{\frac{s_d}{\sqrt{n}}} = \frac{8.21 - 0}{\frac{7.90}{\sqrt{14}}} = 3.881 \]

### The Paired $t$-Test (d)}

*  Procedure is two-tailed, and you can assume a significance level of 5\%.
*  It is also a small sample procedure (n=14, hence df = 13).
*  The Critical value is determined from statistical tables (2.1603).
*  Decision Rule: Reject Null Hypothesis ($|TS|>CV$). Significant difference in measurements before and after.

<p>

### The Paired $t$-Test (e)
Alternative Approach : using p-values.

*  The p-values are determined from computer code. (We will use a software called <tt>R</tt>. Other types of software inlcude \texttt{SAS} and \texttt{SPSS}.)
*  The null and alternative are as before.
*  The computer software automatically generates the appropriate test statistic, and hence the corresponding p-value.
*  The user then interprets the p-values. If p-value is small, reject the null hypothesis. If the p-value is large, the appropriate conclusion is a failure to reject $H_0$.
*  The threshold for being considered small is less than $\alpha/k$, (usually 0.0250). (This is a very arbitrary choice of threshold, suitable for some subject areas, not for others)

### The Paired $t$-Test (h)

*  We could also consider the confidence interval. We are $95\%$ confident that the expected value of the case-wise difference is at least 3.65.
*  Here the null value (i.e. 0) is not within the range of the confidence limits.
*  Therefore we reject the null hypothesis.

<pre><code>
> t.test(Before,After,paired=TRUE)
...
...
95 percent confidence interval:
  3.650075 12.778496
...
</code></pre>

### The Paired $t$-Test (f)
Implementing the paired t-test using <tt>R</tt> for the example previously discussed.
<pre><code>
> t.test(Before,After,paired=TRUE)

        Paired t-test

data:  Before and After
t = 3.8881, df = 13, p-value = 0.001868
alternative hypothesis: true difference in means is not 0
95 percent confidence interval:
  3.650075 12.778496
sample estimates:
mean of the differences
               8.214286

</code></pre>

<p>

### The Paired $t$-Test (g)

*  The p-value ($0.001868$) is less than the threshold is less than the threshold $0.0250$.
*  We reject the null hypothesis (mean of case-wise differences being zero, i.e. expect no difference between ``before" and ``after").
*  We conclude that there is a difference between `before' and `after'.
*  That is to say, we can expected a difference between two paired measurements.

