Package ‘cdata’
October 21, 2018
Type Package
Title Fluid Data Transformations
Version 1.0.3
Date 2018-10-20
URL https://github.com/WinVector/cdata/,
https://winvector.github.io/cdata/
Maintainer John Mount <jmount@win-vector.com>
BugReports https://github.com/WinVector/cdata/issues

#### Description 
 Supplies higher-order fluid data transform operators that include pivot and anti-
pivot as special cases.
The methodology is describe in 'Zumel', 2018, ``Fluid data reshap-
ing with 'cdata''', <http://winvector.github.io/FluidData/FluidDataReshapingWithCdata.html> , doi:10.5281/zenodo.117329
Based on the 'DBI' database interface.

* License GPL-3
* Encoding UTF-8
* LazyData true
* RoxygenNote 6.1.0
* Depends R (>= 3.4.0)
* Imports wrapr (>= 1.6.3), rquery (>= 1.1.0), stats
* Suggests DBI, RSQLite, testthat, knitr, rmarkdown, data.table (>=
1.11.4), rqdatatable (>= 1.1.1)
* VignetteBuilder knitr
* ByteCompile true
8 NeedsCompilation no
* Author John Mount [aut, cre],
Nina Zumel [aut],
Win-Vector LLC [cph]
* Repository CRAN
* Date/Publication 2018-10-21 07:40:03 UTC

#### R topics documented:
blocks_to_rowrecs . . . . .
blocks_to_rowrecs_q . . . .
build_pivot_control . . . . .
build_pivot_control_q . . . .
build_unpivot_control . . . .
cdata . . . . . . . . . . . . .
checkColsFormUniqueKeys
map_fields . . . . . . . . . .
map_fields_q . . . . . . . .
pivot_to_rowrecs . . . . . .
qlook . . . . . . . . . . . .
rowrecs_to_blocks . . . . .
rowrecs_to_blocks_q . . . .
unpivot_to_blocks . . . . . 
