---
title: "American Community Survey For Idaho"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(digits=3)
```

## Question 1
The American Community Survey distributes downloadable data about United States communities. 
Download the 2006 microdata survey about housing for the state of Idaho using download.file() from here: 

<pre><code>
https://dl.dropbox.com/u/7710864/data/csv_hid/ss06hid.csv

or here:

https://spark-public.s3.amazonaws.com/dataanalysis/ss06hid.csv 
</code></pre>

and load the data into R. 



% You will use this data for the next several questions. 

### Code Book 

The code book, describing the variable names is here: 

<pre><code>
https://dl.dropbox.com/u/7710864/data/PUMSDataDict06.pdf

The code book, describing the variable names is here: 

https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FPUMSDataDict06.pdf 
</code></pre>



How many housing units in this survey were worth more than \$1,000,000?
% **53**

%


<p>


How many housing units in this survey were worth more than $1,000,000?
2076
31
53
25



%<pre><code>
%# Download 2006 microdata survey 
%# re: housing for Idaho using download.file()
%# setwd("~/DA")
%download.file(
%'https://spark-public.s3.amazonaws.com/dataanalysis/ss06hid.csv',
%"ss06hid.csv", method="curl")
%
%# Download the code book:
%# download.file(
%'https://spark-public.s3.amazonaws.com/dataanalysis/PUMSDataDict06.pdf',
%"PUMSDataDict06.pdf", method="curl")
%</code></pre>
%

<p>

<pre><code>
# load the data into R
idahoData <- read.csv("ss06hid.csv", header=TRUE)

# Is it just Idaho data?
table(idahoData$ST)
#Check the PDF - what does 16 mean?

#any missing data?
summary(idahoData$ST)

# How many housing units are worth
# more than $1,000,000?
table(idahoData$TYPE,idahoData$VAL)
</code></pre>


<p>


<pre><code>
#from local files
idahoData <- read.csv("daquiz2.csv", header=TRUE)

</code></pre>

<p>

## Question 2

Use the data you loaded from Question 1. Consider the variable FES in the code book. Which of the "tidy data" principles does this variable violate?
Tidy data has one observation per row.
Tidy data has one variable per column.
Numeric values in tidy data can not represent categories.
Each variable in a tidy data set has been transformed to be interpretable.

------------------------------------------------------------------------------------------

## Question 4


* Use the data you loaded from Question 3. 
* Consider the variable FES. 
* Which of the "tidy data" principles does this variable violate?


%%READY
%\textbf{\textit{Revision}}\\
%What are the three characteristics of tidy data?
%
%
%* ``\textit{\textbf{Tidy data}}" by Hadley Wickham (RStudio)
%* Submission to Journal of Statistical Software
%* (http://vita.had.co.nz/papers/tidy-data.pdf)
%
%Three Principles from Hadley Wickham's paper
%
%\item[1.] Each variable forms a column, 
%\item[2.] Each observation forms a row, 
%\item[3.] Each table/file stores data about one kind of observation.
%


<pre><code>
# let's look!
unique(idahoData$FES)
</code></pre>
 

--------------------------------------------------------------

##  Question 5 


### Options

\item[(i)]  Each tidy data table contains information about only one type of observation.\\
(Not so)

\item[(ii)]  Each variable in a tidy data set has been transformed to be interpretable.
(No)

\item[(iii)]  Tidy data has no missing values.

\item[(iv)]  Tidy data has one variable per column.


----------------------------------------------------------------

## Question 5 

Use the data you loaded from Question 3. 

* How many households have 3 bedrooms and and 4 total rooms? 
* How many households have 2 bedrooms and 5 total rooms? 
* How many households have 2 bedrooms and 7 total rooms?




% **148, 386, 49**


<pre><code>
#USING TABLE
#Rooms on Rows , Bedrooms on Columns
#dnn adds dimension names

table(idahoData$RMS,idahoData$BDS,
    dnn=list("RMS","BDS"))

</code></pre>

<[>
Another Way of Doing it

<pre><code>
# How many households have 3 bedrooms and 4 total rooms?
nrow(idahoData[!is.na(idahoData$BDS) & idahoData$BDS==3 &
!is.na(idahoData$BDS) & idahoData$RMS==4,])

# How many households have 2 bedrooms and 5 total rooms?
nrow(idahoData[!is.na(idahoData$BDS) & idahoData$BDS==2 &
!is.na(idahoData$BDS) & idahoData$RMS==5,])

# How many households have 2 bedrooms and 7 total rooms?
nrow(idahoData[!is.na(idahoData$BDS) & idahoData$BDS==2 &
!is.na(idahoData$BDS) & idahoData$RMS==7,])

</code></pre>

--------------------------------------------------------------

### Question 6


* Use the data from Question 3. 
* Create a logical vector that identifies the households on greater than 10 acres who sold more than \$10,000 worth of agriculture products. 
* Assign that logical vector to the variable `\texttt{agricultureLogical}`. 
* Apply the `<tt>which()</tt> function like this to identify the rows of the data frame where the logical vector is `TRUE`.
* Apply the <tt>which()</tt> function like this to identify the rows of the 
data frame where the logical vector is TRUE and assign it to the variable indexes. 

-----------------------------------------------


<pre><code>
# Like this (this wont run yet)
which(agricultureLogical) 
</code></pre>
 

-----------------------------------------------

What are the first 3 values that result?


<pre><code>
# Showing off a bit
q6cols <- c("ACR", "AGS")
which(names(idahoData) %in% q6cols)  

# logical vector
agricultureLogical <- idahoData$ACR==3 & idahoData$AGS==6

# and:
which(agricultureLogical) 
</code></pre>
 

%**125, 238, 262**




-----------------------------------------------



<pre><code>
indexes =  which(agricultureLogical) 
</code></pre>
 

If your data frame for the complete data is called \texttt{dataFrame} you can create a data frame 
with only the above subset with the command: 


-----------------------------------------------

<pre><code>
subsetDataFrame  = dataFrame[indexes,] 
</code></pre>
 

Note that we are subsetting this way because the NA values in the variables 
will cause problems if you subset directly with the logical statement. 

-----------------------------------------------


How many households in the subsetDataFrame have a missing value for the mortgage status 
(MRGX) variable?


<pre><code>
indexes <- which(agricultureLogical)
subsetIdahoData <- idahoData[indexes,]

# And then:
nrow(subsetIdahoData[is.na(subsetIdahoData$MRGX),])
</code></pre>

-----------------------------------------------

## Question 8

* Use the data from Question 3.
* Apply `\texttt{strsplit()}` to split all the names of the data frame on the characters "wgtp". 
* What is the value of the 123 element of the resulting list?



<pre><code>
List <- strsplit(names(idahoData), "wgtp")
List[123]
</code></pre>
 

%**"" "15"**

-----------------------------------------------

## Question 9

What are the 0\% and 100\% quantiles of the variable \texttt{YBL}? Is there anything wrong with these values?
<i> Hint: you may need to use the \texttt{na.rm} parameter.</i>


<pre><code>
quantile(idahoData$YBL, na.rm=TRUE)
#  0%  25%  50%  75% 100% 
#  -1    3    5    7   25 
</code></pre>
 
-----------------------------------------------

## Question 10

In addition to the data from Question 3, the American Community Survey also collects data about populations. 
Using `\texttt{download.file()}`, download the population record data from: 

<pre><code>
https://dl.dropbox.com/u/7710864/data/csv_hid/ss06pid.csv 

or here:

https://spark-public.s3.amazonaws.com/dataanalysis/ss06pid.csv
</code></pre>


-----------------------------------------------



* Load the data into <tt>R</tt>. Assign the housing data from Question 3 to a data frame `\texttt{housingData}` and the population data from above to a data frame `populationData`.

* Use the merge command to merge these data sets based only on the common identifier "SERIALNO". 

* What is the dimension of the resulting data set? 

%[OPTIONAL] For fun, you might look at the data and see what happened when they merged.




%download.file(
%'https://spark-public.s3.amazonaws.com/dataanalysis/ss06pid.csv',
%'ss06pid.csv', method='curl')
%

### Merging Data Sets

<pre><code>

housingData <- read.csv("ss06hid.csv", header=TRUE)
popuData <- read.csv("ss06pid.csv", header=TRUE)

dim(merge(housingData, 
popuData, by="SERIALNO", all=TRUE))
</code></pre>
 




------------------------------------------------------------------

## Question 3
Download the Excel spreadsheet on Natural Gas Aquisition Program here: 

https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FDATA.gov_NGAP.xlsx 

Read rows 18-23 and columns 7-15 into R and assign the result to a variable called:
 dat 
What is the value of:
 sum(dat$Zip*dat$Ext,na.rm=T) 
(original data source: http://catalog.data.gov/dataset/natural-gas-acquisition-program)
184585
36534720
NA
338924

--------------------------------------------------------------------------------

## Question 4
Read the XML data on Baltimore restaurants from here: 

https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Frestaurants.xml 

How many restaurants have zipcode 21231?
156
181
127
100

----------------------------------------------------------------------------------------------------------

## Question 5

The American Community Survey distributes downloadable data about United States communities. 
Download the 2006 microdata survey about housing for the state of Idaho using download.file() from here: 

https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06pid.csv 

using the fread() command load the data into an R object
 DT 
Which of the following is the fastest way to calculate the average value of the variablepwgtp15 
broken down by sex using the data.table package?

tapply(DT$pwgtp15,DT$SEX,mean)
DT[,mean(pwgtp15),by=SEX]
sapply(split(DT$pwgtp15,DT$SEX),mean)
rowMeans(DT)[DT$SEX==1]; rowMeans(DT)[DT$SEX==2]
mean(DT$pwgtp15,by=DT$SEX)
mean(DT[DT$SEX==1,]$pwgtp15); mean(DT[DT$SEX==2,]$pwgtp15) n