R Environment {data-navmenu="R Environment"}
=======================================

Column {.tabset}
---------------------------------------

### Time and Date functions

The commands ``Sys.time()`` and ``Sys.Date()`` returns the system's idea of the current date with and without time.
We can perform some simple algebraic calculations to compute time differences (i.e. to find out how long some code took to compile.)

<pre>
<code>
> X1=Sys.time()
> #Wait a few seconds
>
> X2=Sys.time()
> X2-X1
Time difference of 8.439614 secs
>
> Sys.Date() 
[1] "2012-09-01"
</code>
</pre>

###  Built-In Data Sets
Several data sets , intended as learning tools, are automatically installed when R is installed.
Many more are installed within packages to complement learning to use those packages. One
of these is the famous Iris data set, which is used in many data mining exercises.
*  iris
*  mtcars
*  Nile
To see what data sets are available, simply type data(). To load a data set, simply type in the
name of the data set. Some data sets are very large. To just see the first few (or last) rows, we
use the head() function or alternatively the tail() function. The default number of rows of
these commands is 6. Other numbers can be specified.
<pre><code>
> head(iris)
Sepal.Length Sepal.Width Petal.Length Petal.Width Species
1 5.1 3.5 1.4 0.2 setosa
2 4.9 3.0 1.4 0.2 setosa
3 4.7 3.2 1.3 0.2 setosa
4 4.6 3.1 1.5 0.2 setosa
5 5.0 3.6 1.4 0.2 setosa
6 5.4 3.9 1.7 0.4 setosa
>
> tail(iris,4)
Sepal.Length Sepal.Width Petal.Length Petal.Width Species
147 6.3 2.5 5.0 1.9 virginica
148 6.5 3.0 5.2 2.0 virginica
149 6.2 3.4 5.4 2.3 virginica
150 5.9 3.0 5.1 1.8 virginic

</code></pre>

In many situations, it is useful to call a particular data set using the attach() command. This
will save having to specify the data sets over repeated operations. The file can then be detached
using the detach() command.

### The ``summary()`` command
The R command summary() is a generic function used to produce result "summaries" of the
results of various objects, from simple vectors to the output of complex model fitting functions.
The function invokes particular methods which depend on the class of the first argument.

<pre><code>
> summary(Nile)
Min. 1st Qu. Median Mean 3rd Qu. Max.
456.0 798.5 893.5 919.4 1032.0 1370.0
>
> summary(Indometh)
Subject time conc
1:11 Min. :0.250 Min. :0.0500
4:11 1st Qu.:0.750 1st Qu.:0.1100
2:11 Median :2.000 Median :0.3400
5:11 Mean :2.886 Mean :0.5918
6:11 3rd Qu.:5.000 3rd Qu.:0.8325
3:11 Max. :8.000 Max. :2.7200

</code></pre> 

### Working directories
You can change your working directly by using the appropriate options on the File menu. To
determine the current working directory, you can use the getwd() command. To change the
working directory , we would use the \texttt{setwd()} command. This is quite important as objects
will be imported and exported to and from the specified directory.
<pre><code>
> getwd()
[1] "C:/Users/Kevin"
>
> setwd("C:/Users/Kevin/Documents")
>
> getwd()
[1] "C:/Users/Kevin/Documents"

</code></pre>

### Coming Unstuck
If you are having trouble with a piece of code that is currently compiling , all you have to do
is press ESC, just like many other computing environments.

###  Quitting the \texttt{R} environment
As the front page text indicates, all you have to do to quite the workspace is to type in \texttt{q()}.
You will then be prompted to save your work.



