Packages
===============
### Using and Installing packages
Many packages come with R. To use them in an R session, you need to load the package. 
For example to load the MASS package which contains functions and datasets that accompany Venables and Ripley, Modern Applied Statistics with S, you use the command:

### Installing additional packages
Some packages are not automatically installed when you install R but they need to be downloaded and installed individually. 
An important example is the 'evd' package that accompanies Fox, Applied Regression. 

Working with R Pacakges
====================================

\begin{itemize}
\item Type `library()` onto the command line to find out what packages were installed on your computer
when you put in `R`. 
\item Now type `search()` to get a list of the packages from that list that are
already loaded in (installed packages are not necessarily loaded in). 
\end{itemize}

Installing R Pacakges
====================================

```{r}
install.package("packagename")
download.package("packagename")
```


