
CS2B Paper H {data-navmenu="R for Risk Modelling and Survival Analysis"}
==============================================================

```{css, echo=FALSE}
pre {
  background: #ADD8E6;
  max-width: 100%;
  overflow-x: scroll;
}
```

Column  {.tabset}
--------------------------------


### Question 1
<h4> Question 1</h4>

The data file “***Expenses.csv***” contains records of last 5 years monthly expenses paid by a 
company starting from January 2015. 
#### Exercises

1. Import the data and classify it as a time series object, specifying the relevant dates.
2.  Assuming that the data shows yearly seasonal variation, remove the seasonality from 
the data using seasonal differencing. 
3.   Plot a graph showing the actual data, the trend line, the trend + seasonal line and any 
remaining un-trended number. Plot them in the same graph and use different colour 
lines for each of the series. 
-------
Import the time series data file “ARIMA.csv” and answer the below questions. 
4.   Plot a graph for the above time series data “ARIMA.csv”.
5.  Plot two graphs to show the ACF and PACF for the time series provided.
6.  Comment on the stationarity of the data based on the above graphs. 

### Question 2
<h4> Question 2</h4>

The file “***Data.csv***” contains records of premium received and claim paid between certain time period. 
The ‘Day’ information represents the date on which the transaction occurred, calculated from the first transaction date. 

#### Exercises

1. Separate the data into two tables – premium and claim, based on the transaction type 
and calculate 

<ol type="a">
<li> mean premium </li>
<li> mean claim amount </li>
<li> standard deviation of premium </li>
<li> standard deviation of claim amount </li>
</ol>
 

2.  It is assumed that the waiting times between consecutive events follow a Poisson 
process. Expand the ‘claim’ table to include a column for observed waiting time (in days) for all the claims and calculate a Poisson parameter value.

#### Video
<ol>
<li><a href="www.youtube.com/watch?v=y5u5Gupi67U">Estimating the Poisson Rate Parameter (R for Actuarial Students)</a></li>
</ol>





### Question 3

Claim size [X] for a class of insurance follows a Gamma (10,0.2) distribution. 

#### Exercises

1. Calculate $f{30}$. 

2.  Calculate the median of the function. 

3.   A quota share reinsurance is in place with 75% retained proportion. Estimate the mean 
and variance of the amount paid by the reinsurer in respect of a single claim.
<p>
The aggregate claim follows a compound distribution with below parameters: 

* Number of claims follow Poisson distribution with parameter 500 
* Individual claim size follows a Gamma distribution with parameters (600,0.3) 
[use <tt>seed = 250</tt> for below 3 questions]. 
4.   Generate 1000 observations and calculate the 500th simulated value. 
 
5.  The insurer wants to limit its claim liability and hence has modified the terms of the 
policy. It would now only pay for any amount in excess of an amount 500 on each 
claim. Calculate the 500th simulated value for the insurer under the revised condition. 

6.  The insurer wants to analyze another claim sharing option. Under this, insurer will pay 
75% of the claim amount and the rest 25% will be borne by the policyholder. 
Calculate the 500th simulated value for the insurer under this option. 

#### Video
<ol>
<li><a href="www.youtube.com/watch?v=ro2yJTnYKPQ">The Gamma Distribution - Usage in Modelling Insurance Claims</a></li>
</ol>


### Question 4

The force of mortality ‘<tt>mu(x)</tt>’ for a particular group of life can be calculated using the 
formula as A*B^x; where A=0.00002; B=exp(c); c=0.09; x denotes the age of the life. 
#### Exercises

1. Write down a formula for mu(x) in R and calculate the value of <tt>mu(50)</tt>. 
2.  If survival probability px can be approximated as $[exp(-mu(x+0.5))]$, calculate the 
probability that a life aged 50, will remain alive after 10 years. 
3.   Create a table of mortality rate qx for ages between 40 to 50. 

### Question 5

A primary school has two wings A and B. The students can change their Wing freely. 
It was observed that the rate of movement is dependent on the age ‘x’ of the student (ranging from 5 to 15). 
The rate of movement from A to B = [0.08*x – 0.2] and the rate of movement from B to A = [0.05 * x + 0.1]. 



#### Exercises

1. Write a code to calculate the generator matrix G(x). Calculate the rate at which a 12 
year old student will move from wing B to A and from A to B. 
2.  Over a very small time period h, the transition probability matrix P(t,t+h) can be 
approximated as $P(t,t+h) = I + h*G(t)$; where $I$ is the identity matrix. 

Using this, calculate the probability that a 8 year old will move to Wing B in next 5 years in case $h=1/365$. 

### Datasets
