### Eigenvalues and Eigenvectors
The eigenvalues and eigenvectors can be computed using the ``eigen()`` function.  A data object is created.
This is a very important type of matrix analysis, and many will encounter it again in future modules.
<code>
Y = eigen(A)
names(Y)
"	y$val are the eigenvalues of A
"	y$vec are the eigenvectors of A
</code>

%----------------------------------------------%1
{Linear Algebra Functions}

\texttt{R} supports many import linear algebra functions such as cholesky 
decomposition, trace, rank, eigenvalues etc.

The required results may be determinable from the output of a command that 
pertains to an overall approach.

The eigenvalues and eigenvectors can be computed using the eigen() function.  
A data object known as a list is then created.

<code>
eigen(A)       #eigenvalues and eigenvectors

qr(A)          #returns Rank of a matrix

svd(A)
</code>
This is a very important type of matrix analysis, and many will encounter 
it again in future modules.



