``summary()`` is particularly useful for manipulating data from more complex data objects.

<p>
The command texttt{summary()} is one of the most useful commands in R. It is a generic function used to produce result summaries of the results of various functions. The function invokes particular methods which depend on the class of the first argument. 
In other words – texttt{R} picks out the most suitable type of summary for that data.
{
	small
<pre>
<code>
> summary(iris)
  Sepal.Length    Sepal.Width     Petal.Length    Petal.Width          Species  
 Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100   setosa    :50  
 1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300   versicolor:50  
 Median :5.800   Median :3.000   Median :4.350   Median :1.300   virginica :50  
 Mean   :5.843   Mean   :3.057   Mean   :3.758   Mean   :1.199                  
 3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800                  
 Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500                  
>
</code>
</pre>
<p>
}

### {3.2 The texttt{summary()} command}
 
*  The command texttt{summary()} is one of the most useful commands in ***R***. 
*  It is a generic function used
 to produce result summaries of the results of various functions. 
*  The function invokes particular
 methods which depend on the class of the first argument. 
*  In other words, ***R*** picks out the most
 suitable type of summary for that data.
 
 
 %==============================================================================================%
 
 
 
 begin{figure}
 centering
 includegraphics[width=0.99linewidth]{images/irissummary}
 
 end{figure}
 texttt{summary()} is particularly useful for manipulating data from more complex data objects.
 
 
 %==============================================================================================%
 
 
