---
title: "``boxcox_trans``: Box-Cox & modulus transformations."
author: "Kevin O'Brien"
date: "19 October 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(scales)
```


#### Description
The Box-Cox transformation is a flexible transformation, often used to transform data towards
normality. The modulus transformation generalises Box-Cox to also work with negative values.

#### Usage

<pre><code>
boxcox_trans(p, offset = 0)
modulus_trans(p, offset = 1)
</code></pre>

#### Arguments
* ``p``: Transformation exponent, $\lambda$.
* ``offset``: Constant offset. 0 for Box-Cox type 1, otherwise any non-negative constant
(Box-Cox type 2). ``modulus_trans()`` sets the default to 1.

#### Details
The Box-Cox power transformation (type 1) requires strictly positive values and takes the following
form for y > 0:

$$f_\lambda (x) = \frac{x^{\lambda} - 1 }{\lambda} $$

When y = 0, the natural log transform is used.

The modulus transformation implements a generalisation of the Box-Cox transformation that works
for data with both positive and negative values. The equation takes the following forms, when
y $\neq$ 0 :
$$y(\lambda) = \textrm{sign}(y) \times \frac{(|y| + 1)^{\lambda} -1 }{\lambda}$$

and when y = 0:
$$y(\lambda) = \textrm{sign}(y) \times \ln(|y| + 1)$$

#### References
* Box, G. E., & Cox, D. R. (1964). An analysis of transformations. Journal of the Royal Statistical
Society. Series B (Methodological), 211-252. https://www.jstor.org/stable/2984418
* John, J. A., & Draper, N. R. (1980). An alternative family of transformations. Applied Statistics,
190-197. http://www.jstor.org/stable/2986305