Matrices {data-navmenu="Maths with R"}
==============================

Column {.tabset}
------------------------------

### Creating a matrix

Matrices can be created using the ``matrix()`` command. The arguments to be supplied are 

* vector of values to be entered
* Dimensions of the matrix, specifying either the numbers of rows or columns.


Additionally you can specify if the values are to be allocated by row or column. By default they are allocated by column.

<pre>
<code>
Vec1=c(1,4,5,6,4,5,5,7,9)# 9 elements
A=matrix(Vec,nrow=3)#3 by 3 matrix. Values assigned by column.
A
B= matrix(c(1,6,7,0.6,0.5,0.3,1,2,1),ncol=3,byrow =TRUE)
B          #3 by 3 matrix. Values assigned by row.
</code>
</pre>
<p>


If you have assigned values by column, but require that they are assigned by row, you can use the transpose function texttt{t()}.
<pre>
<code>
t(A)# Transpose
A=t(A)
</code>
</pre>
<p>



Another method of creating a matrix is to “bind” a number of vectors together, either by row or by column. The commands are texttt{rbind() }.and texttt{cbind()} respectively.


<pre>
<code>
x1 =c(1,2) ; x2 = c(3,6)
rbind(x1,x2)
cbind(x1,x2)
</code>
</pre>
<p>







Particular rows and columns can be accessed by specifying the row number or column number, leaving the other value blank.
<code>
A[1,]  # access first row of A
B[,2]   # access first column of B
</code>

### Addition and subtractions
For matrices, addition and subtraction works on an element- wise basis. The first elements of the respective matrices are added, and so on.
A+B
A-B

Matrix Multiplication
To multiply matrices, we require a special operator for matrices; "%       * %".
If we just used the normal multiplication, we would get an element-wise multiplication.
A         * B  #Element-wise multiplication
A %       * % B  #Matrix multiplication
We can compute crossproducts using the crossprod () command. If only one matrix is used it
<pre>
<code>
crossprod(A,B) # A'B
crossprod(A) # A'A
</code>
</pre>
<p>

	
<p>
Determinants, Inverse Matrices and solving Linear systems
To compute the determinant of a square matrix, we simply use the det() command
det(A)
det(B)
To find the inverse of a square matrix, we use the solve() command, specifying only the matrix in question
solve(A)

To solve a system of linear equations in the form Ax=b , where A is a square matrix, and b is a column vector of known values, we use the solve() command to determine the values of the unknown vector x.
b=vec2  # from before
solve(A, b)

### Row and Column Statistics.
Statistic on the rows and columns can easily be computed if required.
%rowMeans(A)  # Returns vector of row means.
%rowSums(A)  # Returns vector of row sums.
%colMeans(A)  # Returns vector of column means.
%colSums(A)  # Returns vector of coumn means.

<p>
### Eigenvalues and Eigenvectors
The eigenvalues and eigenvectors can be computed using the eigen() function.  A data object is created.
This is a very important type of matrix analysis, and many will encounter it again in future modules.

Y = eigen(A)
names(Y)
"y$val are the eigenvalues of A
"y$vec are the eigenvectors of A

?
Part 2 Revision on Earlier Material
"Accessing a column of a data frame
"Accessing a row of a data frame

A particular row can be accessed by specifying the row index , while leaving the column index empty

Info [4,]# Fourth row of "Info" is called

A sequence of rows can be accessed by specifying a sequence of rows as follows.

Info [10:15,]# tenth row to fifteenth row of "Info" is called








Particular rows and columns can be accessed by specifying the row number or column number, leaving the other value blank.
<code>
A[1,]	  # access first row of A
B[,2]   # access first column of B
</code>
Addition and subtractions
For matrices, addition and subtraction works on an element- wise basis. The first elements of the respective matrices are added, and so on.
A+B
A-B

Matrix Multiplication
To multiply matrices, we require a special operator for matrices; "%       * %".
If we just used the normal multiplication, we would get an element-wise multiplication.
A         * B  		#Element-wise multiplication
A %       * % B  	#Matrix multiplication
We can compute crossproducts using the crossprod () command. If only one matrix is used it
<pre>
	<code>
	crossprod(A,B) 		# A'B
	crossprod(A) 			# A'A
	</code>
</pre>
<p>


Linear Algebra {data-navmenu="Maths with R"}
==============================

Column {.tabset}
------------------------------

### Determinants, Inverse Matrices and solving Linear systems
To compute the determinant of a square matrix, we simply use the det() command
det(A)
det(B)
To find the inverse of a square matrix, we use the solve() command, specifying only the matrix in question
solve(A)

To solve a system of linear equations in the form Ax=b , where A is a square matrix, and b is a column vector of known values, we use the solve() command to determine the values of the unknown vector x.
b=vec2  # from before
solve(A, b)

<p>

A particular row can be accessed by specifying the row index , while leaving the column index empty

Info [4,]			# Fourth row of "Info" is called

A sequence of rows can be accessed by specifying a sequence of rows as follows.

Info [10:15,]		# tenth row to fifteenth row of "Info" is called
