
%---------------------------------------------------------------------------------%

\begin{frame}[fragile]{Vectors}
\begin{itemize}
\item $R$ operates on named data structures. The simplest such
structure is the vector, which is a single entity consisting of an
ordered collection of numbers or characters.

\item The most common types of vectors are:
\begin{itemize}
\item Numeric vectors \item Character vectors \item Logical
vectors
\end{itemize}

\item There are, of course, other types of vectors.
\begin{itemize}
\item Colour vectors - potentially useful later on.
\item Order vectors - The rankings of items in a vector.
\item Complex number vectors - not part of this course.
\end{itemize}
\end{itemize}
\end{frame}
%---------------------------------------------------------------------------------%
\begin{frame}[fragile]
\frametitle{Vectors: Creating and editing a vector}
\begin{itemize}
\item From last class.
\item To create a vector, use the assignment operator ``$=$" or ( $<-$ )and
the concatenate function ``c()". \item For numeric vectors, the values
entered are simply numbers.
\begin{framed}
\begin{verbatim}
>x =c(10.4,5.6,3.1,6.4,8.9)
>
\end{verbatim}
\end{framed}
% And, from last week, we can use the ``data.entry()" function to edit our vector.
% \begin{verbatim}
% >data.entry(x)
% >
% \end{verbatim}
\end{itemize}
\end{frame}



%---------------------------------------------------------------------------------%
\begin{frame}[fragile]
\frametitle{Vectors: Character \& logical vector}

\begin{itemize}
\item For character vectors, the values are simply characters,
specified with quotation marks.
\item Single quotation marks
\begin{framed}
\begin{verbatim}

Charvec <- c(`Dog', `Cat', `Shed', `Spoon')

\end{verbatim}
\end{framed}

\item A logical vectors is a vector whose elements are TRUE, FALSE
or NA (i.e. null)
%---------------------------------------------------------------------------------%

### {Vectors}

*  $R$ operates on named data structures. The simplest such
structure is the vector, which is a single entity consisting of an
ordered collection of numbers or characters.

*  The most common types of vectors are:

*  Numeric vectors *  Character vectors *  Logical
vectors


*  There are, of course, other types of vectors.

*  Colour vectors - potentially useful later on.
*  Order vectors - The rankings of items in a vector.
*  Complex number vectors - not part of this course.


