
<p>
### {Vector types}
R operates on named data structures. 
The simplest such structure is the vector, which is a single entity consisting of an ordered collection of
Numbers or characters.


Numeric vectors
Character vectors
Logical vectors
(also complex number vectors and colour vectors)


To create a vector, use the assignment operator and the concatenate function.
For numeric vectors, the values are simply numbers.

<code>
># week8.r
>NumVec<-c(10.4,5.6,3.1,6.4)
</code>

Alternatively we can use the ``assign()`` command

For character vectors, the values are simply characters, specified with quotation marks.A logical vectors is a vector whose elements are TRUE, FALSE or NA

<code>
>CharVec<-c(``blue", ``green", ``yellow")
>LogVec<-c(TRUE, FALSE)
</code>

<p>
### {Graphical data entry interface}

``Data.entry()`` is a useful  command for inputting or editing data sets. 
Any changes are saved automatically (i.e. don't need to use the assignment operator). 
We can also used the ``edit()`` command, which calls the ``R Editor``.

<code>
>data.entry(NumVec)
>NumVec <- edit(NumVec)
</code>

Another method of creating vectors is to use the following
<code>
numeric (length = n)
character (length = n)
logical (length = n)
</code>
These commands create empty vectors, of the appropriate kind, of length $n$. 
You can then use the graphical data entry interface to populate your data sets.


#### {Accessing specified elements of a vector}

The $n$th element of vector ***Vec*** can be accessed by specifying its index when calling ``Vec".
<code>
  Vec[n]
</code>
A sequence of  elements of vector ``Vec" can be accessed by specifying its index when calling ``Vec".
<code>>Vec[l:u]
</code>
<p>
Omitting and deleting the $n$th element of vector ``Vec"
<code>
>Vec[-n]
>Vec <- Vec[-n]
</code>
