### Missing Data

In some cases the components of a vector may not be
completely known. When an element or value is 'not available' or a 'missing value' in the statistical sense, a place within a vector
may be reserved for it by assigning it the special value NA.

In general any operation on an NA becomes an NA.
The motivation for this rule is simply that if the specification of an operation is incomplete, the result cannot be known and hence is not available.
<p>
The command ``is.na()`` can be used to determine whether there
are any missing values in a data set, by means of a logical
vector.

<pre><code>
> is.na(x)
[1] FALSE FALSE FALSE FALSE FALSE
</code></pre>


 %==============================================================================================%

 \frametitle{2.10 Missing Data}
 
 *  In some cases the entire contents of a vector may not be known. For example, missing data
 from a particular data set. *  A place can be reserved for this by assigning it the special value
 NA.
 NA is a logical constant of length 1 which contains a missing value indicator.
 *   NA stands
 for Not Available.
 *  Missing values can adversely affect calculations. Add \texttt{na.rm=T} to commands
 
 
 \texttt{mean(X,na.rm=T)}
 

