
### Grubbs Test for Determining an Outlier}

The Grubbs test is used to determine if there are any outliers in a data set.\\ \bigskip
There is no agreed formal definition for an outlier. The definition of outlier used for this procedure is a value that unusually distance from the rest of the values ( For the sake of clarity , we shall call this type of outlier a \textbf{Grubbs Outlier}). Consider the following data set: is the lowest value 4.01 an outlier?
\begin{verbatim}
6.98 8.49 7.97 6.64
8.80 8.48 5.94 6.94
6.89 7.47 7.32 4.01
\end{verbatim}

Under the null hypothesis, there are no outliers present in the data set. 
We reject this hypothesis if the p-value is sufficiently small.


%-------------------------------------------------%

### Grubbs Test for Determining an Outlier}
\begin{verbatim}
> grubbs.test(x, two.sided=T)
Grubbs test for one outlier
data: x
G = 2.4093, U = 0.4243, p-value = 0.05069
alternative hypothesis: lowest value 4.01 is an outlier
\end{verbatim}
We conclude that while small by comparison to the other values, the lowest value 4.01 is not an outlier.


\end{document}


Kolmogorov Smirnov Tests
Non-parametric procedures
Compute the test statistic
Same distribution
