

CS1B Paper K {data-navmenu="R for Actuarial Statistics"}
==============================================================

Column {.tabset}
--------------------------------


### Question 1

<h4>Question 1</h4>
An engineer is considering the maximum number of people who can occupy a lift. In 
particular, the engineer wants to assess the probability of exceeding a maximum 
weight when eight people are allowed to use the lift at the same time, compared to 
nine people. 
Assume that: 
* the total weight of eight people chosen at random follows a normal distribution 
with a mean of 560 kg and standard deviation of 57 kg 
* the total weight of nine people chosen at random follows a normal distribution 
with a mean of 630 kg and standard deviation of 61 kg.



#### Exercises

1. Calculate the probability that the total weight of eight people exceeds 650 kg.
  
2. Calculate the probability that the total weight of nine people exceeds 650 kg.
  
3. Comment on your answers to parts (i) and (ii).  

4. Calculate the interval for the central region containing 80% of the distribution 
of the total weight of eight people.
Assume now that the total weight of eight people chosen at random follows a gamma 
distribution with parameters α = 96.5220 and λ = 0.1724. 

5. (a) Calculate the interval for the central region containing 80% of the 
distribution of the total weight of eight people in this case. 
(b) Comment on your answers to parts (iv) and (v)(a). 




### Question 2

<h4>Question 2</h4>

Simulate a sample of 100 values from a Beta distribution with 
parameters $a = 3$, $b = 1$. Use the command <tt>set.seed(12345)</tt> to 
initialise the random number generator, before you start the simulation. 



#### Exercises 
(b) Plot a histogram of the sample simulated in part (i)(a). 
(c) Comment on the shape of the histogram produced in part (i)(b). 



(ii) (a) Perform 1,000 repetitions of the simulation in part (i)(a). 
You should compute and store the value of the mean of the sample for each 
repetition. 

Use the command <tt>set.seed(12345)</tt> to initialise the 
random number generator, before you start the simulation. 
(b) Plot a histogram of the 1,000 sample means computed in part (ii)(a). 



(c) Comment on the shape of the histogram produced in part (ii)(b) by 
referring to a fundamental statistical property.  
For the remaining parts of the question consider the following small sample of data 
(given here in R code): 
<pre><code>
y <- c(4.9, 3.3, 2.2, 2.3, 1.6, 2.4, 4.7, 1.4, 1.7, 5.1) 
</code></pre>
3. Determine a 90% confidence interval for the population mean of these data, 
stating any assumptions that you make. [3] 
4. Determine an estimate of the standard error of the sample mean using these 
data.  



(v) Determine an estimate of the standard error of the sample mean using 
bootstrap with a bootstrap sample size of 10,000. 

Use the command 
<tt>set.seed(12345)</tt> to initialise the random number generator, before you 
start the bootstrap sampling. 

(vi) (a) Determine a bootstrap 90% confidence interval for the population 
mean of the y data using the same bootstrap sample as in part (v). 
(b) Comment on the two confidence intervals produced in parts (iii) and 
(vi)(a). 
 


### Question 3

<h4>Question 3</h4>


