CS1B Paper F {data-navmenu="R for Actuarial Statistics"}
==============================================================

Column {.tabset}
--------------------------------

### Question `1
Use the ‘MotorClaims’ dataset provided to answer the following questions: 
(MotorClaims.csv. 

#### Exercises 
1.  Fit Gamma distribution on the dataset provided by determining its scale and shape 
parameters. State clearly the distribution with the parameters. 
2.  Simulate 1000 values from the distribution obtained in exercise 1 and print the first six values. (Set seed to 100) 
3.  Calculate the mean and variance of simulated values. 
4.  Obtain a QQ plot for the simulations of 1000 values and a normal distribution. 
5.  Add a line to the above plot to show the true position of normal distribution. 
6.  Comment on the shape of the distribution and how close it is to a normal distribution. 

### Question 2
<h4> Question 2</h4>
The dataset ‘mtcars’ (built into R) consists of data on various models of car, taken from an 
American motoring magazine (1974 Motor Trend magazine). For each car, there are certain 
features expressed in varying units.
1.  Load the ‘mtcars’ dataset which is built into R. How many observations and variables 
are there in this dataset? Your answer should include the R output. 
2.   Identify the categorical variables from the dataset ‘mtcars’ and create a dataset 
excluding the categorical variables. 
3.    How many observations and variables are there in the new dataset? Your answer 
should include the R output. 
4.  Carry out a principal component analysis on the new dataset of mtcars by passing two 
arguments, ‘center’ and ‘scale’ to be TRUE. Your answer should include a summary 
of the principal component analysis. 
5.  How many components of the reduced data should be retained using the output 
derived in part 4 ? Also state the reason for the same. 

### Question 3
Data is provided for ‘***BMIClaims***’ of 150 policyholders and corresponding claim count. 
(BMIClaims.cs5. .
 
1. Obtain 95% confidence interval for the standard deviation of BMI (using ***qchisq()***). 
2. Further test the standard deviation of BMI to be equal to 4 by obtaining p value. State your conclusion of the test. 
3. If obese is defined to be BMI above 30, use <tt>binom.test()</tt> to calculate 99% confidence interval for proportion of obese people and comment on the likelihood if more than 20 pc are obese. 
4.  Claim frequency can be calculated as claim count divided by number of policyholders. 
Test whether claim frequency is different between obese and others. 

### Question 4
The CDC and EISS detect influenza activity through clinical data including Influenza-like Illness (IL1.  physician visits on weekly basis. 
The objective of this question is to estimate influenza-like illness (IL1.  activity using Google web search logs.
<p>

#### Data
The csv file ***FluTrain.csv*** aggregates this data from January 1, 2004 until December 31, 2011 
as follows:
* "Week" - The range of dates represented by this observation, in year/month/day format.
* "ILI" - This column lists the percentage of ILI-related physician visits for the corresponding week.
* "Queries" - This column lists the fraction of queries that are ILI-related for the corresponding week, adjusted to be between 0 and 1 (higher values correspond to more ILI-related search 
queries).

#### Exercises
1.  Plot a histogram of the dependent variable, ILI. Comment on the shape of the 
distribution. 
2.  Plot the natural logarithm of ILI versus Queries. What does the plot suggest? 
3.  Fit a linear regression model for dependent variable log(IL1. . Summarize it. 
4.  State the formula of the model fitted in exercise 3, explaining all the terms used. 
5.  Calculate R-squared and the correlation between the independent and dependent variable. What is the relationship between the two values? 
6.  Looking at the time period 2004-2011, which week corresponds to the highest percentage of ILI-related physician visits? 
7.  Based on the linear regression model fitted in exercise 3, what is the estimate for the percentage of ILI-related physician visits for the week computed in exercise 6.  ? 
8.  What is the relative error between the estimate (prediction calculated in part 7 and the actual observed value for the week computed in exercise 6 ? 

### Data 
CS1B_BMIClaims
http://www.actuariesindia.org/downloads/Year_2020_November_Exam/CS1B_BMIClaims.csv
CS1B_FluTrain
http://www.actuariesindia.org/downloads/Year_2020_November_Exam/CS1B_FluTrain.csv
CS1B_MotorClaims
http://www.actuariesindia.org/downloads/Year_2020_November_Exam/CS1B_MotorClaims.csv
