CS2B Paper D {data-navmenu="R for Risk Modelling and Survival Analysis"}
==============================================================

Column {.tabset}
--------------------------------




### Question 1
<h4> Question 1 </h4>

Monthly totals of airline passengers are given in time series data ‘AirPassengers’. 

#### Exercises 
1.  Plot the data as time series with <tt>frequency =12</tt> (i.e. 12 months). 

2.   Plot the acf function. 

3.    Decompose the trend, seasonality and randomness for the data.
(Hint: use <tt>decompose()</tt> function.) 

4.  Fit Arima model.

(Hint: <tt>order=c(1,0,0), list(order=c(2,1,0), period=12</tt> as parameters.) 

5.  Predict the data for next 24 months. 

6.   Find upper and lower bound of fitted data and plot the same along with predicted data 
with legends. 

#### Video
<ol>
<li><a href="www.youtube.com/watch?v=C6skIO5Thyo">AirPassengers - Time Series Plots</a></li>
</ol>


### Question 2
<h4> Question 2 </h4>

#### Exercises 

1. Draw the graph of hazard function for the gamma distribution with parameters $\alpha  = 0.75$  and $\lambda = 0.5$. 
2. Draw the graph of hazard function for the gamma distribution with parameters $\alpha  = 1$ and $\lambda = 0.5$. 
3. Draw the graph of hazard function for the gamma distribution with parameters $\alpha  = 1.5$ and $\lambda = 0.5$. 
4. Comment on the thickness of the tails of the distribution of 2.   with the tails of exercises 1 and 3
(For the graphs, the value of $x$ varies from 0 to 10).


#### Video
<ol>
<li><a href="www.youtube.com/watch?v=sH5Fhg68Bto">Hazard Functions and Survival Functions for the Gamma Distribution</a></li>
</ol>



### Question 3
<h4> Question 3 </h4>
Mortality of a group of lives follows Gompertz’s law. The value of the parameters is known 
as c = 1.128 & B = 7.29 x 10-6
.
Use the approximation 
$$  f ( t ) = a e − e b − c t {\displaystyle f(t)=a\mathrm {e} ^{-\mathrm {e} ^{b-ct}}}$$
where

* a is an asymptote, since $ {\textstyle \lim _{t\to \infty }a\mathrm {e} ^{-\mathrm {e} ^{b-ct}}=a\mathrm {e} ^{0}=a}$
* b sets the displacement along the x-axis (translates the graph to the left or right).
* c sets the growth rate (y scaling)
* e is Euler's Number (e = 2.71828...)
	
#### Exercise
Calculate an approximate of the curtate value 
for age 55 or e55. 

Assuming 100 is the maximum age. 

### Question 4
<h4> Question 4 </h4>
An life insurance company is selling Endowment, Pure Term and Unit Linked products wherein 80% of the business comes from Endowment, 5% from Term Insurance and 15% 
from Unit Linked products. The sum assured ranges between 30000 to 200000 with multiple 
of 5000. 

The sum assured are normally distributed with below parameters 
* Endowment (mean 50000, standard deviation 10000), 
* Pure Term (mean 100000, standard deviation 25000), 
* Unit Linked (mean 60000, standard deviation 5000). 

One policy is randomly picked from the system and the sum assured of that policy is 75000. 

#### Exercises

1.  Create a sequence ranging from 30000 to 200000 with an increase of 5000 and plot the 
density functions of the above three distributions in a single graph. 
2.   Find the probability that the policy (75000 sum assured) comes from the Endowment 
product portfolio and the probability that the policy comes from Unit Linked Product 
portfolio. 

### Question 5
<h4> Question 5 </h4>
Signals are mathematically represented by a function that takes into account the magnitude 
and frequency.
$$xt = A cos(2π\omega t + \ph1.  + wt,$$ where $\omega$  is equal to 1/50 and wt is the white noise with mean 
zero and SD of 5. $A$ and $\phi$ need to be estimated.
In this case the parameters appear in a nonlinear way, so we use a trigonometric identity 
and write

$$
A cos(2π\omega t + \ph1.  = A cos(\ph1.  cos(2π\omega t) - A sin(\ph1.  sin(2π\omega t),\\
= β1 cos(2π\omega t) + β2 sin(2π\omega t),\\
= β1*z1 + β2*z2\\
$$

If we can estimate β1 and β2, then A and $\phi$ can be estimated.
Therefore, $xt = β1 cos(2π\omega t) + β2 sin(2π\omega t) + wt $

#### Exercises
1. Simulate and plot a series xt, using A=2, \phi = 0.6π and SD of white noise as 5 (for t= 1 
to 1000). 
2. Generate two series z1 and z2 (for t= 1 to 1000). 
3.  Fit a Linear model to between xt, z1 and z2 and estimate parameters β1, β2 , A and \phi. 
4.  Plot $x$, fitted line. 

### Question 6
<h4> Question 6 </h4>
Suppose the transition probabilities are a function of the age of a person. The transition 
probability of a person aged x moving:
* from Healthy to Sick state is 0.007x 
* from Healthy to Death state is 0.001x 
* from Sick to Death state is 0.002(100-x) 
* from Sick to Healthy is 0.006(100-x). 

#### Exercises

Assuming 100 is the maximum age. Calculate the probability of: 

1. Healthy person aged 30 will be in Sick state after 4 years. 
2. Sick person aged 25 will be in Death state after 7 years. 

#### Video
<ol>
<li><a href="www.youtube.com/watch?v=eHQA6fkp1DQ">Transition Matrices for Actuarial Forecasting</a></li>
</ol>




### Exercise 7
<h4> Question 7 </h4>
An extract from the data for 15 patients monitored in hospital after every 15 minutes post 
giving them a dosage of life saving drug is shown in the table below. 

```{r eval=FALSE}
Person Last time at which patient was 
observed (time unit in 15 Minutes) Outcome

```

$$
\begin{array}{|c||c|c|}
\hline
1 & 6  & Died \\ \hline
2 & 6 & Discharged \\ \hline
3 & 12 & Died \\ \hline
4 & 18 & Discharged \\ \hline
5 & 27 & Died \\ \hline
6 & 27 & Discharged \\ \hline
7 & 30 & Discharged \\ \hline
8 & 36 & Discharged \\ \hline
9 & 39 & Died \\ \hline
10 & 39 & Discharged \\ \hline
11 & 54 & Discharged \\ \hline
12 & 57 & Died \\ \hline
13 & 60 & Survived \\ \hline
14 & 60 & Survived \\ \hline
15 & 60 & Survived \\ \hline
\end{array}
$$
#### Exercises
1.  Use the data to create the Kaplan-Meier estimate of the survival function. Use the 
“{Survival}” library in R to create the summary of the model (survival rates, standard 
deviation, lower 95% confidence interval, upper 95% confidence interval). 
2.   Use the results of the summary created in exercise 1 and input the values of $t_j$, $d_j$ and $n_j$ in the 
model to calculate the estimated integrated hazard and hence the Nelson ‐ Aalen 
estimate of the survival model. 
3.    Create a table to compare the above two analysis. 

### Exercise 8
Consider a set of data generated by tossing a fair coin, letting $x_t = 1$ when a head is obtained 
and xt = −1 when a tail is obtained. Then, construct yt as
$$yt = 2 + 1.5xt − 0.5xt−1$$

#### Exercises 
Simulate data for three cases, one with a small sample size (n = 10), another one with a 
moderate sample size (n = 100) and lastly with large sample size (n = 1000).

1.  Plot the series for all three cases. 
2.  Find the mean and variance and comment on results. 
