Package ‘janitor’
July 31, 2018
Title Simple Tools for Examining and Cleaning Dirty Data
Version 1.1.1
#### Description The main janitor functions can: perfectly format data.frame column
names; provide quick counts of variable combinations (i.e., frequency
tables and crosstabs); and isolate duplicate records. Other janitor functions
nicely format the tabulation results. These tabulate-and-report functions
approximate popular features of SPSS and Microsoft Excel. This package
follows the principles of the ``tidyverse'' and works well with the pipe function
%>%. janitor was built with beginning-to-intermediate R users in mind and is
optimized for user-friendliness. Advanced R users can already do everything
covered here, but with janitor they can do it faster and save their thinking for
the fun stuff.
URL https://github.com/sfirke/janitor
BugReports https://github.com/sfirke/janitor/issues
Depends R (>= 3.1.2)
Imports dplyr (>= 0.7.0), tidyr (>= 0.7.0), snakecase (>= 0.9.0),
magrittr, purrr, rlang
License MIT + file LICENSE
LazyData true
RoxygenNote 6.0.1.9000
Suggests testthat, knitr, rmarkdown
VignetteBuilder knitr
NeedsCompilation no
Author Sam Firke [aut, cre],
Chris Haid [ctb],
Ryan Knight [ctb],
Bill Denney [ctb]
Maintainer Sam Firke <samuel.firke@gmail.com>
Repository CRAN
Date/Publication 2018-07-31 04:30:02 UTC
1
2 add_totals_col
R topics documented:
add_totals_col . . . . 2
add_totals_row . . . 3
adorn_crosstab . . . 3
adorn_ns . . . . . . . 4
adorn_pct_formatting 5
adorn_percentages . 5
adorn_rounding . . . 6
adorn_title . . . . . . 7
adorn_totals . . . . . 8
as_tabyl . . . . . . . 9
clean_names . . . . . 10
convert_to_NA . . . 11
crosstab . . . . . . . 12
excel_numeric_to_date . . . . . . . . . . . 13
get_dupes . . . . . . 14
janitor_deprecated . . 14
remove_empty . . . 15
remove_empty_cols . 15
remove_empty_rows 16
round_half_up . . . . 16
row_to_names . . . . 17
tabyl . . . . . . . . . 18
top_levels . . . . . . 19
untabyl . . . . . . . 20
use_first_valid_of . . 20
Index 22
