``adorn_title`` Add column name to the top of a two-way tabyl.
#### Description
This function adds the column variable name to the top of a tabyl for a complete display of information.
This makes the tabyl prettier, but renders the data.frame less useful for further manipulation.

#### Usage 
<pre><code>
adorn_title(dat, placement = "top", row_name, col_name)
</code></pre> 

#### Arguments
* ``dat``: a data.frame of class tabyl or other data.frame with a tabyl-like layout. If given
a list of data.frames, this function will apply itself to each data.frame in the list
(designed for 3-way tabyl lists).

* placement whether the column name should be added to the top of the tabyl in an otherwiseempty
row "top" or appended to the already-present row name variable ("combined").
The formatting in the "top" option has the look of base R’s table(); it also
wipes out the other column names, making it hard to further use the data.frame
besides formatting it for reporting. The "combined" option is more conservative
in this regard.
row_name (optional) default behavior is to pull the row name from the attributes of the
input tabyl object. If you wish to override that text, or if your input is not a
tabyl, supply a string here.
col_name (optional) default behavior is to pull the column_name from the attributes of the
input tabyl object. If you wish to override that text, or if your input is not a
tabyl, supply a string here.

#### Value
the input tabyl, augmented with the column title. Non-tabyl inputs that are of class tbl_df are
downgraded to basic data.frames so that the title row prints correctly.

#### Examples
```
mtcars %>%
tabyl(am, cyl) %>%
adorn_title(placement = "top")
```

```{r}
# Adding a title to a non-tabyl
library(tidyr); library(dplyr)
mtcars %>%
group_by(gear, am) %>%
summarise(avg_mpg = mean(mpg)) %>%
spread(gear, avg_mpg) %>%
adorn_title("top", row_name = "Gears", col_name = "Cylinders")
```
